(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var r3=function(a){a.Z("cardstatechange",a.Dh()&&a.nk()?1:0)},s3=function(a,b){var c=g.Ka(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},hNa=function(a){var b=g.Zl(a);
a=g.em(a);return new g.Jl(b.x,b.y,a.width,a.height)},iNa=function(a){return Math.pow(a,3)},jNa=function(a){return 3*a*a-2*a*a*a},v3=function(a){a=g.Na(a);
delete t3[a];g.Wb(t3)&&u3&&u3.stop()},lNa=function(){u3||(u3=new g.M(function(){kNa()},20));
var a=u3;a.isActive()||a.start()},kNa=function(){var a=g.Pa();
g.Fb(t3,function(b){mNa(b,a)});
g.Wb(t3)||lNa()},w3=function(a,b,c,d){g.Tq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.K=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.J=0;this.C=null},mNa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.C);a.C=b;nNa(a,a.progress);1==a.progress?(a.Ta=0,v3(a),a.onFinish(),a.dw()):a.zc()&&a.tB()},nNa=function(a,b){"function"===typeof a.D&&(b=a.D(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.K[c]-a.i[c])*b+a.i[c]},oNa=function(a,b){g.rf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.Ta},x3=function(a,b,c,d,e){w3.call(this,b,c,d,e);
this.element=a},y3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
x3.call(this,a,b,c,d,e)},z3=function(a){g.I.call(this);
this.u=a||window;this.i=[]},A3=function(a){return a.baseUrl||null},B3=function(a,b){return g.Io(g.wm(a,b,void 0),function(c){return!!c})},pNa=function(a,b,c){function d(ha){var va,kb,Pb,Eb=ha.hovercardButton;
if(!Eb)return null;Eb=Eb.subscribeButtonRenderer;if(!Eb)return null;var ac=f(Eb.unsubscribedButtonText),Qb=f(Eb.subscribedButtonText);if(Eb.subscribed){var Oe=f(Eb.subscriberCountWithUnsubscribeText);var Pe=f(Eb.subscriberCountText)}else Oe=f(Eb.subscriberCountText),Pe=f(Eb.subscriberCountWithSubscribeText);var bc=null;return ha.signinEndpoint&&(bc=s3(ha,"signinEndpoint","webNavigationEndpointData","url"),bc||(bc=null===(Pb=null===(kb=null===(va=Eb.signInEndpoint)||void 0===va?void 0:va.commandMetadata)||
void 0===kb?void 0:kb.webCommandMetadata)||void 0===Pb?void 0:Pb.url),!bc)?null:ac&&(Qb||bc)?{subscribed:Eb.subscribed,subscribeText:ac,subscribeCount:Oe,unsubscribeText:Qb,unsubscribeCount:Pe,enabled:Eb.enabled,signinUrl:bc,classic:ha.useClassicSubscribeButton}:null}
function e(ha){if(ha){var va=[],kb=ha.videoId;kb&&va.push("v="+kb);(kb=ha.playlistId)&&va.push("list="+kb);(ha=ha.startTimeSeconds)&&va.push("t="+ha);return"/watch?"+va.join("&")}}
function f(ha){if(!ha)return null;var va=ha.simpleText;return va?va:ha.runs?g.wm(ha.runs,function(kb){return kb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,q=null,t=null,u=null,x=!1,y=null,A=null,D=null,F=null,H=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,q=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=s3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):A=f(b.subscribersText)}else"WEBSITE"===
h?((D=s3(l,"urlEndpoint","url"))&&(m=D),n=!0,p="new",D=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(H=f(b.additionalFeesText)),(n=s3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=s3(b,"title","accessibility","accessibilityData","label");var K=b.endpoint?b.endpoint.clickTrackingParams:null,Y="";if(b.metadata){var L=f(b.metadata);L&&(Y=L)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Y,callToAction:f(b.callToAction),SI:b.image,
iconUrl:D,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:q,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:A,isSubscribe:x,targetUrl:m||null,QR:n,sessionData:K?{itct:K}:null,LW:p,nu:a?a:null,TR:b.isPlaceholder,impressionUrls:B3(b.impressionUrls||[],A3),JR:B3(b.hovercardShowUrls||[],A3),clickUrls:B3(l.loggingUrls||[],A3),visualElement:g.ry(b.trackingParams),
productPrice:F,additionalFeesText:H}},C3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:B3(a.impressionUrls||[],A3),elements:B3(a.elements||[],function(d,e){return pNa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.ry(a.trackingParams));return c},D3=function(a){g.gN.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.V=!0;this.J=0;a=a.U();this.N=g.nF(a)||g.rF(a);this.events=new g.ID(this);g.J(this,this.events);this.events.S(this.player,g.AA("creatorendscreen"),this.Fd);this.events.S(this.player,g.BA("creatorendscreen"),this.uf);this.events.S(this.player,"resize",this.yb);this.events.S(window,"focus",this.PV);this.load();var b=g.wg("STYLE");(g.ig("HEAD")[0]||document.body).appendChild(b);g.qf(this,function(){g.Ag(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},qNa=function(a){return a.player.getVideoData().D?"current":a.N?"new":"current"},E3=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},rNa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=C3(f,qNa(a))));F3(a,f)},
urlParams:{v:c},withCredentials:!0};a.N&&(c.urlParams.ptype="embedded");var d=b.Qp;d&&(c.postParams={ad_tracking:d});if(b=g.Moa(b))if(b=g.Qc(b),b=g.Mc(b))a.B=g.ot(b,c)},F3=function(a,b,c){c=void 0===c?!0:c;
a.player.bf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&sNa(a);c=[];d=new g.xA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().i||(a.u=new g.V({G:"div",L:"ytp-ce-shadow"}),g.XM(a.player,a.u.element,4),a.C=new g.KL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=tNa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.XM(a.player,f.element,4);var h=new g.xA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);uNa(a,f,e)}else g.sz(new g.aw("buildEndscreenElement null",
e))}a.player.Md(c);a.yb()}},sNa=function(a){var b=g.vy(),c=g.yy();
c&&b&&a.endscreen.visualElement&&g.zz(void 0,c,b,[a.endscreen.visualElement])},tNa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.Y("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ia:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.nu||"","aria-hidden":"true"},T:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:G3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:H3(a,b.targetUrl),tabindex:"-1"},T:[{G:"div",Ia:["ytp-ce-video-title"].concat(g.v(c)),W:{dir:g.br(b.title||
"")},xa:b.title},{G:"div",L:"ytp-ce-video-duration",xa:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.Y("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ia:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.nu||"","aria-hidden":"true"},T:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:G3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:H3(a,
b.targetUrl),tabindex:"-1"},T:[{G:"div",Ia:["ytp-ce-playlist-title"].concat(g.v(c)),W:{dir:g.br(b.title||"")},xa:b.title},{G:"div",L:"ytp-ce-playlist-count",T:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={G:"div",Ia:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.nu||"","aria-hidden":"true"},T:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",T:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",T:[{G:"div",L:"ytp-ce-expanding-overlay-body",T:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",T:[{G:"a",Ia:["ytp-ce-channel-title","ytp-ce-link"],W:{href:H3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.br(b.title||"")},xa:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",T:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{G:"div",Ia:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:G3(b)}]};c=new g.V(c);var d=g.jg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.N(d,"ytp-ce-subscribe-button");if(a.player.U().i){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.lO(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ia:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.nu||"","aria-hidden":"true"},T:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",T:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",T:[{G:"div",L:"ytp-ce-expanding-overlay-body",T:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",T:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.br(b.title||"")},xa:b.title},{G:"div",L:"ytp-ce-website-metadata",xa:b.metadata},{G:"a",Ia:["ytp-ce-website-goto","ytp-ce-link"],W:{href:H3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:G3(b)},{G:"div",
L:"ytp-ce-expanding-icon",W:vNa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",T:[{G:"div",L:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.T.push({G:"div",L:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={G:"div",Ia:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.nu||"","aria-hidden":"true"},T:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
T:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",T:[{G:"div",L:"ytp-ce-expanding-overlay-body",T:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",T:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.br(b.title||"")},xa:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",xa:b.metadata},{G:"a",Ia:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:H3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",W:G3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",T:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",xa:b.callToAction||void 0}]}]},c=new g.V(a)}b.TR&&g.N(c.element,"ytp-ce-placeholder");return c},G3=function(a){if(a.SI)var b=a.SI.thumbnails;
return vNa(b?b[b.length-1].url:null)},vNa=function(a){return a?{style:"background-image: url("+a+")"}:{}},uNa=function(a,b,c){function d(m){m&&(b.Sa("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.N(b.element,"ytp-ce-force-expand"),I3(a,c.id,!0)):(g.Qq(b.element,"ytp-ce-force-expand"),g.Qq(b.element,"ytp-ce-element-hover"),I3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Sa("mouseenter",function(){J3(a,b,c)});
b.Sa("mouseleave",function(){K3(a,b,c)});
a.player.U().i||b.Sa("click",function(){g.N(b.element,"ytp-ce-element-hover")});
b.Sa("click",function(m){wNa(a,c,m)});
b.Sa("keypress",function(m){wNa(a,c,m)});
b.Sa("focus",function(){J3(a,b,c)});
b.Sa("blur",function(){K3(a,b,c)});
b.Sa("touchstart",function(){J3(a,b,c)});
var l=g.lg("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Qq(b.element,"ytp-ce-element-hover");g.Qq(b.element,"ytp-ce-force-expand")});
b.Sa("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.lg("ytp-sb-subscribe",b.element));d(g.lg("ytp-sb-unsubscribe",b.element));b.Sa("focus",f);b.Sa("blur",h)},wNa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Oq(d,"ytp-ce-element");){g.Oq(d,"subscribe-label")&&L3(a,b);
if(g.Oq(d,"ytp-ce-channel-subscribe"))return;d=g.Bg(d)}if(!d||g.Oq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])K3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.LW)L3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Qc(H3(a,b.targetUrl)),c=g.Mc(c),g.LJ(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=H3(a,b.targetUrl),l=b.sessionData,m=g.zs(h);e&&m&&(m.v||m.list)?a.player.Oj(m.v,l,m.list,!1):
g.KJ(h,l)};
L3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},H3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.QF(a)+b}else return"";return b},J3=function(a,b,c){g.Oq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.N(b.element,"ytp-ce-element-hover"):a.player.U().i?(new g.M(function(){g.N(b.element,"ytp-ce-element-hover")},200)).start():g.N(b.element,"ytp-ce-element-hover"),M3(a,c.JR),I3(a,c.id,!0))},K3=function(a,b,c){g.Qq(b.element,"ytp-ce-element-hover");
g.Qq(b.element,"ytp-ce-force-expand");I3(a,c.id,!1)},I3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.i[e].element,"ytp-ce-element-shadow-show",c)},M3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||E3(a))c&&c();else{b=xNa(a,b);var e=0,f=!1,h=new g.M(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Pu(b[a],d)}},L3=function(a,b,c){M3(a,b.clickUrls,c);
(a=g.yy())&&b.QR&&g.Iz(a,b.visualElement)},xNa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(yNa(b[d],c));return a},yNa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},zNa=function(a){return Array.isArray(a)&&a.length?a[0]:a},N3=function(a){return"string"===typeof a?a:""},O3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},ANa=function(a){this.externalId=a},BNa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},P3=function(a){return a.value?a.value:null},Q3=function(a){if(!a)return null;
var b=g.Qc(N3(a.value));b=g.Mc(b);if(!b)return null;var c=O3(a.target,CNa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new BNa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},DNa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},GNa=function(a){if(!a)return null;
var b=O3(a.type,ENa),c=O3(a.trigger,FNa),d=zNa(a.url);d=Q3(d?d:null);a=zNa(a.subscribeData);var e=a?a:null;e?(a=N3(e.external_user_id),e=N3(e.subscription_token),a=a&&e?new ANa(a):null):a=null;return b?new DNa(b,c,d,a):null},R3=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},HNa=function(a,b){return g.eb(a.action,b,void 0)},INa=function(a,b){this.context=a;
this.i=b},T3=function(a){return a.customMessage?S3("div","iv-card-message",a.customMessage):""},U3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},T:c}},V3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(S3("li","",c.value));return{G:"ul",L:"iv-card-meta-info",T:b}},S3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.br(c);return{G:a,W:b,xa:c}},JNa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Bx&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Bx+");");c.dir=g.br(a.customMessage);var d=[{G:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ia:b,W:c,T:d}},W3=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},KNa=function(a,b){this.merchant=a;
this.price=b},LNa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},MNa=function(a,b){return b?b:LNa(a)?"current":"new"},X3=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.fb=!1;this.Qa=new Map;this.Ua=new Map;this.context.I.addEventListener(g.AA("annotations_module"),function(d){(d=c.Qa.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.BA("annotations_module"),function(d){(d=c.Ua.get(d))&&d.apply(c)})},Y3=function(a,b,c,d,e,f,h){a.context.i.Sa(b,"click",function(l){a.uB(c,d,e,f||[],h||0,l)});
a.context.i.Sa(b,"touchstart",function(){a.fb=!1});
a.context.i.Sa(b,"touchmove",function(){a.fb=!0})},NNa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},Z3=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
TM:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
sA:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},b4=function(a,b,c){X3.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Ma=this.qb=this.B=this.Xd=!1;this.ya=null;this.cards=[];this.sb=this.N=this.Ha=this.D=this.La=this.i=null;this.ea=[];this.K=this.xe=this.Ca=null;this.J=0;this.Ba=new g.M(g.Ha,c.X.Xc?4E3:3E3);g.J(this,this.Ba);this.eb=new g.M(g.Ha);g.J(this,this.eb);this.ma=new INa(c,function(e,f,h,l,m,n){Y3(d,e,f,h,l,m,n)});
this.V=new g.V({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},T:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},T:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ia:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.J(this,this.V);this.C=this.V.element;this.Ya=new g.KL(this.V,330);g.J(this,this.Ya);this.ib=g.lg("iv-drawer-header-text",this.C);this.u=g.lg("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.qb&&$3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.qb=d.B)&&a4(d)})},ONa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){$3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){a4(a)});
var c=b.headerText;g.Dg(a.ib,c);a.N&&a.N.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ca=g.ry(b.trackingParams);a.K=g.ry(b.closeTrackingParams);a.xe=g.ry(b.iconTrackingParams)},PNa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.GA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.command),Cl:d.trackingParams?g.ry(d.trackingParams):null,Qi:e.trackingParams?
g.ry(e.trackingParams):null,xe:f&&f.trackingParams?g.ry(f.trackingParams):null,imageUrl:d4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.GA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Bx:null,title:d.title?g.GA(d.title):"",customMessage:d.callToAction?g.GA(d.callToAction):"",url:d.command.urlEndpoint.url?Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};e4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.GA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.endpoint),Cl:d.trackingParams?g.ry(d.trackingParams):null,Qi:e.trackingParams?g.ry(e.trackingParams):null,xe:f&&f.trackingParams?
g.ry(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.GA(d.customText):null,profileImageUrl:d4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.GA(d.channelName):"",metaInfo:[d.subscriberCountText?g.GA(d.subscriberCountText):""],url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
e4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.GA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.action),Cl:d.trackingParams?g.ry(d.trackingParams):
null,Qi:e.trackingParams?g.ry(e.trackingParams):null,xe:f&&f.trackingParams?g.ry(f.trackingParams):null,Uw:d4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.GA(d.customMessage):null,playlistVideoCount:g.GA(d.playlistVideoCount),title:d.playlistTitle?g.GA(d.playlistTitle):"",metaInfo:[d.channelName?g.GA(d.channelName):"",d.videoCountText?g.GA(d.videoCountText):""],url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:NNa(d.action)})};e4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.GA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.action),Cl:d.trackingParams?g.ry(d.trackingParams):null,Qi:e.trackingParams?g.ry(e.trackingParams):null,xe:f&&f.trackingParams?g.ry(f.trackingParams):
null,Uw:d4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.GA(d.lengthString):null,customMessage:d.customMessage?g.GA(d.customMessage):null,title:d.videoTitle?g.GA(d.videoTitle):"",metaInfo:[d.channelName?g.GA(d.channelName):"",d.viewCountText?g.GA(d.viewCountText):""],isLiveNow:!!d.badge,url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:NNa(d.action)})};e4(a,b)}a.J++},d4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},c4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},RNa=function(a,b){if(b=QNa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.Ag(b.kC),g.ob(a.cards,b),a.Dx(),f4(a)},$3=function(a,b,c){if(!a.B){a.Ya.show();
a.La=new g.M(function(){g.N(a.context.I.getRootNode(),g.XT.IV_DRAWER_OPEN)},0);
a.La.start();a.ya=g.nu(a.u,"mousewheel",function(h){a.Ba.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.yy();d&&a.Ca&&a.K&&g.Gz(d,[a.Ca,a.K]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.AK||(f.AK=!0,SNa(a.context.logger,f.card.tracking.impression,b)),d&&g.Gz(d,[f.card.Cl]);r3(a.I);c&&(a.D=new g.M(function(){a.Ha=a.N;a.sb.focus()},330),a.D.start())}},a4=function(a){a.B&&(a.Ya.hide(),g.ou(a.ya),a.ya=null,g.Qq(a.context.I.getRootNode(),g.XT.IV_DRAWER_OPEN),a.B=!1,r3(a.I),a.D&&a.D.stop(),a.D=new g.M(function(){a.Ha&&(a.Ha.focus(),a.Ha=null)},330),a.D.start())},
UNa=function(a){g.Pq(a.element,[g.XT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.XM(a.I,a.C,5);TNa(a);a.N=g.lg("ytp-cards-button",a.I.getRootNode());a.sb=g.lg("iv-drawer-close-button",a.C);a.Xd=!0},TNa=function(a){var b=g.lg("iv-drawer-close-button",a.C);
a.context.i.Sa(b,"click",a.uQ,a);a.context.i.Sa(a.u,"touchend",function(){a.Ba.start()});
a.context.i.Sa(a.u,"scroll",a.GQ,a);a.context.u.subscribe("onHideControls",function(){a.Ma=!0});
a.context.u.subscribe("onShowControls",function(){a.Ma=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ma=g.Oq(a.I.getRootNode(),"ytp-autohide")});
a.ea.push(g.Wu("iv-button-shown",a.cS,a));a.ea.push(g.Wu("iv-button-hidden",a.bS,a));a.ea.push(g.Wu("iv-teaser-shown",a.UO,a));a.ea.push(g.Wu("iv-teaser-hidden",a.dS,a));a.ea.push(g.Wu("iv-teaser-clicked",a.TO,a))},e4=function(a,b){a.Xd||UNa(a);
RNa(a,b.id);var c=VNa(a,b);if(c){var d={card:b,kC:c.element,AK:!1},e=WNa(a,d);g.ub(a.cards,e,0,d);c.Fa(a.u,e);a.Dx();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,f4(a),XNa(a,d),$3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&YNa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){YNa(a,d)}),f4(a))}},VNa=function(a,b){switch(b.type){case "simple":a=a.ma;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=JNa(b);c={G:"div",Ia:["iv-card"],T:[{G:"a",L:"iv-click-target",W:{href:b.url?P3(b.url)||"":""},T:[U3(b.imageUrl,c),{G:"div",L:"iv-card-content",T:[S3("h2",void 0,b.title),d]}]}]};c=new g.V(c);W3(a,g.kg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ma,c={G:"div",Ia:["iv-card","iv-card-channel"],T:[{G:"a",Ia:["iv-click-target"],W:{href:P3(b.url)||"","data-ytid":b.channelId},T:[U3(b.profileImageUrl),
{G:"div",L:"iv-card-content",T:[T3(b),{G:"h2",L:"iv-card-primary-link",xa:b.title},V3(b)]}]}]},c=new g.V(c),W3(a,g.kg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ma,c={G:"div",Ia:["iv-card","iv-card-playlist"],T:[{G:"a",L:"iv-click-target",W:{href:P3(b.url)||""},T:[U3(b.Uw,{G:"div",L:"iv-card-image-overlay",T:[{G:"span",L:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",T:[T3(b),S3("h2","iv-card-primary-link",b.title),V3(b)]}]}]},c=new g.V(c),
W3(a,g.kg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ma;var e=!g.jb(b.offers);c=["iv-card"];d="";var f=JNa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",xa:f.merchant}),f={G:"div",T:e});e=b.url?P3(b.url)||"":"";c={G:"div",Ia:c,W:{tabindex:"0"},T:[{G:"a",Ia:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",T:[b.sponsored?{G:"div",L:"iv-card-sponsored",T:["Sponsored",{G:"div",L:"iv-ad-info-container",T:[{G:"div",L:"iv-ad-info",xa:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",T:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},T:[S3("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.wg("span");g.Dg(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.jd(d,"adInfo");W3(a,g.kg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ma,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",xa:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ia:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null,e={G:"div",Ia:["iv-card","iv-card-video"],T:[{G:"a",L:"iv-click-target",W:{href:(null===(c=b.url)||void 0===c?void 0:P3(c))||""},T:[U3(b.Uw,d),{G:"div",L:"iv-card-content",T:[T3(b),S3("h2","iv-card-primary-link",b.title),V3(b),f]}]}]},c=new g.V(e),
W3(a,g.kg("iv-click-target",c.element),b,b.url),c;default:return null}},WNa=function(a,b){if(0===a.cards.length)return 0;
a=g.fb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},ZNa=function(a){return a.i?"productListing"===a.i.card.type:g.xm(a.cards,function(b){return"productListing"===b.card.type})},f4=function(a){g.O(a.I.getRootNode(),"ytp-cards-shopping-active",ZNa(a))},YNa=function(a,b){if(!g.Oq(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.yy(),d=a.i?a.i.card.xe:a.xe;
c&&d&&g.Hz(c,[d]);a.i=b;f4(a)}if(c="none"!=a.element.style.display)a.context.I.U().experiments.oa("html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.I.getPresentingPlayerType()?(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.I.getAdState();c&&b.card.teaserDurationMs&&a.I.Rs(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.eb.isActive()||((!a.B||!a.Ba.isActive()&&a.Ma)&&XNa(a,b),a.eb.start(910+b.card.teaserDurationMs))}},
XNa=function(a,b){a.V.Ab?(b=new w3([0,
a.u.scrollTop],[0,b.kC.offsetTop],600,jNa),a.context.B.Sa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Sa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.aL(a.V,!0),a.u.scrollTop=b.kC.offsetTop,g.aL(a.V,!1))},g4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},QNa=function(a,b){return g.eb(a.cards,function(c){return c.card.id===b})},h4=function(a,b,c){X3.call(this,a,b);
this.annotation=c;this.isActive=!1},$Na=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},i4=function(a,b,c){h4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.J=this.D=null},aOa=function(a,b){var c=void 0===c?0:c;
var d=hNa(b).width;g.Xl(b,d);c=new y3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,iNa);g.J(a,c);a.context.B.Sa(c,"begin",function(){g.fm(b,!0)});
c.play()},dOa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ia:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({G:"div",Ia:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.lO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.I),a.i.Fa(d));var f=a.createElement({G:"div",Ia:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ia:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.fm(h,!1);var l=a.createElement({G:"div",Ia:["branding-context-container-outer"]});l.appendChild(h);g.Ql(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.M(function(){bOa(a,h,l)},500);
g.J(a,a.B);a.context.i.Sa(a.element,"mouseover",function(){cOa(a,h,l,f,b.image_height)});
a.context.i.Sa(a.element,"mouseout",function(){a.B.start()})}},cOa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.em(b);a.i||(b.style.width=g.Wl(f.width,!0),c.style.width=g.Wl(f.width,!0));g.Ql(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Ql(d,"right","1px");a.C=!0;g.fm(b,!0);a.D=new g.M(function(){g.N(this.element,"iv-branding-active")},0,a);
a.D.start()}},bOa=function(a,b,c){g.Qq(a.element,"iv-branding-active");
a.J=new g.M(function(){g.fm(b,!1);a.i||(c.style.width=g.Wl(0,!0))},250);
a.J.start();a.C=!1},eOa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.X=c;this.videoData=d;this.logger=e;this.I=f;this.u=h},j4=function(a,b,c){h4.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.V=!1;this.J=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ia:["iv-promo-contents"]});this.D=new g.M(function(){d.i.setAttribute("aria-hidden","true");g.fm(d.B,!1);g.fm(d.u,!0)},700,this);
g.J(this,this.D)},fOa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=a.annotation.Vd(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ia:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&Y3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.pd(f,P3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",T:[{G:"strong",
xa:b.text_line_1}]});var m=a.createElement({G:"p",T:[{G:"span",L:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ia:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ia:["iv-button","iv-promo-button"],T:[{G:"span",L:"iv-button-content",xa:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&Y3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.N(a.i,
"iv-click-target");e&&Y3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",T:[{G:"span",xa:b.text_line_1}]}),m=a.createElement({G:"p",T:[{G:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ia:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.N(a.i,"iv-click-target"),e&&Y3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.K.appendChild(a.i);p&&
a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ia:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.i.Sa(a.u,"click",function(q){k4(a,5E3,q)});
c.appendChild(a.u);g.fm(a.u,!1);a.context.i.Sa(a.element,"mouseover",a.mR,a);a.context.i.Sa(a.element,"mouseout",a.lR,a);a.context.i.Sa(a.element,"touchend",function(q){k4(a,5E3,q)});
a.B=a.createElement({G:"button",Ia:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.i.Sa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.hR:a.gR,a);c.appendChild(a.B);g.Pq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},k4=function(a,b,c){c.stopPropagation();
gOa(a);hOa(a,b);a.i.focus()},iOa=function(a){a.isCollapsed||a.N||a.C||(g.N(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},gOa=function(a){a.D.stop();
a.isCollapsed&&(g.Rq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.fm(a.u,!1),g.fm(a.B,!0))},hOa=function(a,b){a.C||(a.C=g.ph(function(){l4(this);
iOa(this)},b,a))},l4=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},jOa=function(a){this.I=a},SNa=function(a,b,c){b&&(c?m4(a,b.map(function(d){return g.Cq(d,c)})):m4(a,b))},m4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Pu(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},n4=function(a){g.gN.call(this,a);
var b=this;this.V=!1;this.loadNumber=0;this.K={};this.logger=new jOa(this.player);this.D=new g.ID(this);this.J=this.B=null;this.events=new g.ID(this);this.N=this.i=null;this.ea=[];g.J(this,this.D);this.D.S(this.player,"onVideoAreaChange",function(){b.Z("onVideoAreaChange")});
this.D.S(this.player,"onHideControls",function(){b.Z("onHideControls")});
this.D.S(this.player,"onShowControls",function(){b.Z("onShowControls")});
this.D.S(this.player,"resize",function(d){b.Z("resize",d)});
this.D.S(this.player,"presentingplayerstatechange",function(d){b.Z("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.VO,this);this.subscribe("resize",this.Cz,this);this.player.U().V.subscribe("vast_info_card_add",this.OL,this);g.J(this,this.events);this.ma=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.V({G:"div",Ia:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.u);g.XM(this.player,this.u.element,4);this.u.hide();this.C=new g.V({G:"div",Ia:["ytp-iv-video-content"]});g.J(this,this.C);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.ma);this.C.element.appendChild(a);this.xq()&&this.load();var c=this.createElement({G:"style"});(g.ig("HEAD")[0]||document.body).appendChild(c);g.qf(this,function(){g.Ag(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},kOa=function(a){a=a.createElement({G:"div",
Ia:["annotation","annotation-type-custom"]});g.fm(a,!1);return a},lOa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.aL(a.u,b);g.aL(a.C,b)},mOa=function(a,b,c){a.V=!0;
a.J=g.ot(b,c)},nOa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.La(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(nOa(a,e))}return c},qOa=function(a){var b=a.player.getVideoData();
if(b.Qa){var c=a.player.U().V.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.gt(h)&&h.responseXML?h.responseXML:null)&&o4(a,h)}};
g.Gu()&&(d.onFinish=oOa(a,d.onFinish));d.postParams={ic_only:"1"};pOa(d,c);a.V=!0;g.ot(b.Qa,d)}}},pOa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Cu&&(a.postParams.ic_coll=b.Cu);b.Hx&&(a.postParams.ic_xml=b.Hx);b.Xw&&(a.postParams.ic_track=b.Xw)},rOa=function(a){var b=new g.V({G:"div"});
g.fm(b.element,!1);var c=new b4(a.player,b.element,p4(a));g.J(c,b);b.Fa(a.u.element);c.Hw();return c},p4=function(a){if(!a.N){var b=new z3(a);
g.J(a,b);var c=new g.hk(a);g.J(a,c);a.N=new eOa(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.pd)}return a.N},o4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.yy();if(e){var f=g.vy();f&&g.zz(void 0,e,f,[g.ry(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=nOa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=O3(f.type,sOa),p=O3(f.style,tOa),q=N3(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=GNa;if(null==u)var x=null;else if(g.Ka(u)){l=[];for(var y=g.r(u),A=y.next();!A.done;A=y.next()){var D=f(A.value);
D&&l.push(D)}x=l}else{var F=f(u);x=F?[F]:[]}e=m&&n?new R3(m,n,p,x,t):null}else e=null}catch(va){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=kOa(f),K=null;switch(l.type){case "branding":if(f.player.U().Eb)break;f.u.element.appendChild(H);K=new i4(H,p4(f),l);break;case "promotion":g.XM(f.player,H,4),K=new j4(H,p4(f),l)}K&&K.Hw();if(f=K)g.J(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=rOa(a),g.J(a,a.i));if("card"===e.type){c=a.i;var Y=e&&e.data&&e.data.card_type;
f=e.data;if(Y)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,TM:l.teaser_impression,sA:l.teaser_click},H=f.tracking_params||{},K=null,Y){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Cl:H.card?g.ry(H.card):null,Qi:H.teaser?g.ry(H.teaser):null,xe:H.icon?g.ry(H.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Cl:H.card?g.ry(H.card):
null,Qi:H.teaser?g.ry(H.teaser):null,xe:H.icon?g.ry(H.icon):null,Uw:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "productListing":f.signin_url&&(K=Q3({target:"current",value:f.signin_url}));Y=[];for(var L=f.offers||[],ha=0;ha<L.length;ha++)Y.push(new KNa(g.wd(L[ha].merchant),g.wd(L[ha].price)));e=
{id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Cl:H.card?g.ry(H.card):null,Qi:H.teaser?g.ry(H.teaser):null,xe:H.icon?g.ry(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Bx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),oaa:K,naa:f.signin_title?f.signin_title:void 0,maa:f.signin_message?f.signin_message:void 0,offers:Y};e4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Cl:H.card?g.ry(H.card):null,Qi:H.teaser?
g.ry(H.teaser):null,xe:H.icon?g.ry(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Bx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,
autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Cl:H.card?g.ry(H.card):null,Qi:H.teaser?g.ry(H.teaser):null,xe:H.icon?g.ry(H.icon):null,Uw:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},e4(c,e)}}else ONa(a.i,e);c=!0}}c&&(r3(a.player),a.Cz())},uOa=function(a,
b){var c=!1;
a.i||(a.i=rOa(a),g.J(a,a.i));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(PNa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.GA(b.headerText):"",g.Dg(c.ib,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ca=b.trackingParams?g.ry(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.ry(b.closeButton.infoCardIconRenderer.trackingParams):null,c.xe=b.icon.infoCardIconRenderer.trackingParams?
g.ry(b.icon.infoCardIconRenderer.trackingParams):null,r3(a.player),a.Cz())},vOa=function(a,b,c,d,e){if(!a.player.U().Eb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new DNa("openUrl","click",new BNa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.GA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.GA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.GA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.GA(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.GA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.GA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new R3(c,"branding","branding",f,d);l=kOa(a);a.u.element.appendChild(l);f=new i4(l,p4(a),f);f.Hw();g.J(f,f);a.K[c]=f}},oOa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.isDisposed()||a.ea.push(g.Du(0,function(){b.apply(null,g.v(d))}))}},wOa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.QM.prototype.Rs=g.ca(17,function(a,b){var c=g.xN(this.vb());c&&c.Rs(a,b)});
var t3={},u3=null;g.Qa(w3,g.Tq);g.k=w3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Ta)this.progress=0,this.coords=this.i;else if(this.zc())return!1;v3(this);this.startTime=a=g.Pa();-1==this.Ta&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.zz();this.ni("play");-1==this.Ta&&this.ni("resume");this.Ta=1;var b=g.Na(this);b in t3||(t3[b]=this);lNa();mNa(this,a);return!0};
g.k.stop=function(a){v3(this);this.Ta=0;a&&(this.progress=1);nNa(this,this.progress);this.ni("stop");this.dw()};
g.k.pause=function(){this.zc()&&(v3(this),this.Ta=-1,this.ni("pause"))};
g.k.Aa=function(){0==this.Ta||this.stop(!1);this.ni("destroy");w3.je.Aa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.tB=function(){this.ni("animate")};
g.k.ni=function(a){this.dispatchEvent(new oNa(a,this))};
g.Qa(oNa,g.rf);g.Qa(x3,w3);x3.prototype.u=g.Ha;x3.prototype.tB=function(){this.u();x3.je.tB.call(this)};
x3.prototype.dw=function(){this.u();x3.je.dw.call(this)};
x3.prototype.zz=function(){this.u();x3.je.zz.call(this)};
g.Qa(y3,x3);y3.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(z3,g.I);z3.prototype.Sa=function(a,b,c,d){c=(0,g.E)(c,d||this.u);a=g.nu(a,b,c);this.i.push(a);return a};
z3.prototype.bz=function(a,b,c,d){c=(0,g.E)(c,d||this.u);a=g.xu(a,b,c);this.i.push(a);return a};
z3.prototype.pc=function(a){g.ou(a);g.ob(this.i,a)};
z3.prototype.Aa=function(){g.ou(this.i);this.i.length=0;g.I.prototype.Aa.call(this)};g.w(D3,g.gN);g.k=D3.prototype;g.k.load=function(){g.gN.prototype.load.call(this);if(!E3(this)){var a=g.Noa(this.player.getVideoData());a?(a=C3(a,qNa(this)),F3(this,a,!1)):rNa(this)}};
g.k.unload=function(){F3(this,null);this.B&&(this.B.abort(),this.B=null);g.gN.prototype.unload.call(this)};
g.k.gf=function(a,b){return E3(this)?"loadCustomEndscreenRenderer"===a?(a=C3(b,"new"),F3(this,a),!0):null:null};
g.k.getOptions=function(){return E3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.yb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<xOa.length;f++){var h=Math.abs(b.width-xOa[f]);if(-1===e||d>=h)e=f,d=h}d=yOa[e];this.u&&g.Ql(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.dm(e.element,Math.round(h.width*a.width),f);g.Xl(e.element,m,n);g.Rq(e.element,zOa);m=h.left+h.width/2;h=h.top+l/2;g.N(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Rq(e.element,yOa);g.N(e.element,d);(e=g.jg(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Ql(e,"height",f+"px")}}}}};
g.k.Fd=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())M3(this,this.endscreen.impressionUrls),(a=g.yy())&&this.endscreen.visualElement&&g.Az(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.N(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.N(b,"ytp-ce-shown");M3(this,c.impressionUrls);(b=g.yy())&&g.Az(b,c.visualElement,void 0);this.player.U().B&&this.player.Na("endscreenelementshown",
a)}};
g.k.uf=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Qq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Qq(b,"ytp-ce-shown");this.player.U().B&&this.player.Na("endscreenelementhidden",a)}};
g.k.PV=function(a){var b=this;a.target===window&&(new g.M(function(){for(var c=g.r(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Rq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var xOa=[346,426,470,506,570,640,853,1280,1920],yOa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),zOa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var CNa={m0:"current",W5:"new"};var ENa={CLOSE:"close",o6:"openUrl",UP:"subscribe"},FNa={FY:"click",CLOSE:"close",H1:"hidden",K7:"rollOut",L7:"rollOver",A8:"shown"};R3.prototype.Vd=function(){var a=HNa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var tOa={ZX:"anchored",FN:"branding",CHANNEL:"channel",k0:"cta",K1:"highlightText",K2:"label",PLAYLIST:"playlist",g7:"popup",J8:"speech",UP:"subscribe",c9:"title",VIDEO:"video",k$:"website"},sOa={FN:"branding",sY:"card",B0:"drawer",J1:"highlight",q4:"marker",q7:"promotion",TEXT:"text",q$:"widget"};g.w(X3,g.I);g.k=X3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.xA(a,b,{id:c});a.namespace="annotations_module";d&&this.Qa.set(a,d);e&&this.Ua.set(a,e);this.context.I.Md([a])};
g.k.Hw=function(){this.context.u.subscribe("resize",this.Dx,this)};
g.k.uB=function(a,b,c,d,e,f){if(this.fb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Ag(this.element)};
g.k.Dx=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=P3(a);if(f){var h=MNa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.D||!1,n=g.zs(f||"");m&&n&&(n.v||n.list)?e.context.I.Oj(n.v,b,n.list,!1):g.LJ(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);m4(this.context.logger,c,l,d);LNa(f)||(c=g.yy(),d=b.itct,c&&d&&g.Iz(c,g.ry(d)))}};
g.k.Aa=function(){this.Qa.clear();this.Ua.clear();g.I.prototype.Aa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.w(b4,X3);g.k=b4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.em(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Dx=function(){var a=this.isAvailable();g.fm(this.element,a);g.O(this.context.I.getRootNode(),g.XT.IV_DRAWER_ENABLED,a);r3(this.I)};
g.k.destroy=function(){this.I.Rs(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.Xu(this.ea);g.ou(this.ya);this.La&&this.La.dispose();this.D&&this.D.dispose();X3.prototype.destroy.call(this)};
g.k.uQ=function(){if(this.B){m4(this.context.logger,g4(this).tracking.close);var a=g.yy();a&&this.K&&g.Iz(a,this.K);a4(this)}};
g.k.GQ=function(){g.O(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.cS=function(){var a=g.yy(),b=g4(this);b=b?b.xe:this.xe;a&&b&&g.Gz(a,[b])};
g.k.bS=function(){var a=g.yy(),b=g4(this);b=b?b.xe:this.xe;a&&b&&g.Hz(a,[b])};
g.k.UO=function(){var a=g4(this);m4(this.context.logger,a.tracking.TM);var b=g.yy();b&&a&&g.Gz(b,[a.Qi,a.xe])};
g.k.dS=function(){var a=g.yy(),b=g4(this);a&&b&&g.Hz(a,[b.Qi])};
g.k.TO=function(a){var b=g4(this),c=g.yy();this.i?a?(a=this.context.logger,m4(a,b.tracking.sA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Qi&&g.Iz(c,b.Qi)):(a=this.context.logger,m4(a,b.tracking.sA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.xe&&g.Iz(c,b.xe)):(a=this.context.logger,m4(a,b.tracking.sA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.xe&&g.Iz(c,this.xe))};g.w(h4,X3);h4.prototype.Hw=function(){X3.prototype.Hw.call(this);$Na(this)};
h4.prototype.show=function(){X3.prototype.show.call(this);var a=g.yy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Gz(a,[g.ry(b.itct)])};
h4.prototype.hide=function(){X3.prototype.hide.call(this);var a=g.yy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Hz(a,[g.ry(b.itct)])};g.w(i4,h4);
i4.prototype.show=function(){if(!this.isActive){h4.prototype.show.call(this);if(!this.K){g.N(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ia:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.fm(this.u,!1);var b=this.createElement({G:"div",Ia:["branding-img-container"]});b.appendChild(this.u);this.element.appendChild(b);(b=this.annotation.Vd())&&Y3(this,this.u,b,this.annotation.id,
a.session_data);dOa(this,a);this.K=!0}g.fm(this.element,!0);this.isActive=!0;this.u&&aOa(this,this.u)}};
i4.prototype.hide=function(){this.isActive&&(h4.prototype.hide.call(this),g.fm(this.element,!1),this.isActive=!1)};
i4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);h4.prototype.destroy.call(this)};g.w(j4,h4);g.k=j4.prototype;g.k.show=function(){this.isActive||(h4.prototype.show.call(this),this.V||(fOa(this),this.V=!0),g.fm(this.element,!0),g.ph(function(){g.Qq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,l4(this),gOa(this),hOa(this,this.J))};
g.k.hide=function(){this.isActive&&(g.N(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.uB=function(a,b,c,d,e,f){return this.isCollapsed?!1:h4.prototype.uB.call(this,a,b,c,d,e,f)};
g.k.mR=function(a){this.N=!0;k4(this,500,a)};
g.k.lR=function(){this.N=!1;iOa(this)};
g.k.gR=function(a){a.stopPropagation();this.hide()};
g.k.hR=function(a){a.stopPropagation();l4(this);this.isCollapsed=!0;g.N(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();h4.prototype.destroy.call(this)};g.w(n4,g.gN);g.k=n4.prototype;g.k.gf=function(a,b){if(!wOa(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.T1(b))&&o4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(RNa(this.i,b),r3(this.player)),!0}return null};
g.k.getOptions=function(){return wOa(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.xq=function(){var a=this.player.U(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.tI||a.V.get(b.videoId)||g.pH(b)||g.qH(b)?!0:!1};
g.k.Cz=function(){if(this.C){var a=this.player.gb().getVideoContentRect(!0);g.dm(this.C.element,a.width,a.height);g.Xl(this.C.element,a.left,a.top)}if(this.i){var b=this.player.jj();a=this.i;b=b.width;g.O(a.C,"iv-drawer-small",426>=b);g.O(a.C,"iv-drawer-big",1280<=b)}};
g.k.VO=function(a){lOa(this,a.state);g.U(a.state,2)&&(this.Dh()&&this.nk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Rs(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.J=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.gt(h)&&h.responseXML?h.responseXML:null)&&(o4(b,h),g.N(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.gN.prototype.load.call(this);lOa(this,this.player.wb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Gu()&&(a=oOa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.J=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().V.get(d);f&&pOa(e,f);f=f&&(f.Hx||f.Cu);if(!c.wl||f)c.Qa?mOa(this,c.Qa,e):(this.B=function(){b.rb(e)},this.player.addEventListener("videodatachange",this.B));
g.XM(this.player,this.C.element,4);this.Cz();(f=g.pH(c))&&uOa(this,f);(f=g.qH(c))&&f.featuredChannel&&vOa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.rb=function(a){var b=this.player.getVideoData();b.Qa&&(this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null),mOa(this,b.Qa,a))};
g.k.unload=function(){this.player.bf("annotations_module");for(var a=g.r(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.N=null;this.i&&(this.i.destroy(),this.i=null,r3(this.player));this.V=!1;this.J&&(this.J.abort(),this.J=null);this.K={};this.u.hide();g.gN.prototype.unload.call(this);this.C.detach();this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null)};
g.k.OL=function(a){a===this.player.getVideoData().videoId&&(this.loaded?qOa(this):this.load())};
g.k.Dh=function(){return!!this.i&&this.i.isAvailable()};
g.k.nk=function(){this.Dh();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Dh();this.i&&(a?c?$3(this.i,c,b):$3(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):a4(this.i))};
g.k.Rs=function(a,b){this.player.Z(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.Aa=function(){this.player.U().V.unsubscribe("vast_info_card_add",this.OL,this);g.Qq(this.player.getRootNode(),g.XT.IV_DRAWER_OPEN);for(var a=this.ea,b=0,c=a.length;b<c;b++)g.Hu(a[b]);this.ea.length=0;g.gN.prototype.Aa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.rN.annotations_module=n4;g.rN.creatorendscreen=D3;})(_yt_player);
