(function(g){var window=this;'use strict';var t4=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},u4=function(a){return g.GF(a)&&a.Y("web_player_i_see_captions_3")},AOa=function(a,b){return g.G(this,function d(){var e,f,h;
return g.B(d,function(l){if(1==l.i)return e=a+"|"+b,g.z(l,g.Zw(),2);if(3!=l.i){f=l.u;if(!f)throw g.jw("gct");return g.z(l,(0,g.hG)(),3)}h=l.u;return l.return(h.get("captions",e))})})},BOa=function(a,b){var c=new g.kG;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},COa=function(a,b,c){AOa(a,b).then(function(d){d&&c(d.trackData,new g.kG(d.metadata))})},v4=function(){this.segments=[]},DOa=function(a,b){var c=g.xb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.nb(a.segments,c),g.nb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.ub(a.segments,c,0,b),g.ub(a.segments,c+1,0,b)))},w4=function(a,b,c,d,e,f){g.I.call(this);
this.policy=a;this.player=b;this.ea=c;this.N=d;this.D=e;this.V=f;this.X=this.player.U();this.C=new v4;this.J=-1;this.B=this.u=this.i=null;this.K=new g.M(this.xK,1E3,this);this.events=new g.ID(this);g.J(this,this.K);g.J(this,this.events);this.events.S(b,"SEEK_COMPLETE",this.FG);this.FG();this.xK()},EOa=function(a){return a.i&&a.i.D?a.i.D+a.player.Sc()<a.player.getCurrentTime():!1},FOa=function(a,b){var c=g.YC(b,a.policy,{}).Vd(),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.B=g.gh(g.ut(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,h=g.ula(e);if(h){e=g.YC(a.u,a.policy,{});a.u.mj(e,h);FOa(a,a.u);break a}f||(h=a.u.i[0].Oa,null!=a.N&&a.J!==h&&(f=a.u.i[0],a.D?a.N(e.response,1E3*(f.startTime+a.player.Sc())):a.N(e.responseText,1E3*(f.startTime+a.player.Sc())),a.J=h))}a.u=null;a.B=null}}),function(){a.u=null;
a.B=null;a.ra()});
a.u=b;DOa(a.C,a.u.i[0].Oa)},x4=function(a,b){g.jN.call(this,b.U());
this.i=a;this.I=b;this.B=null;this.D=!1;this.J=g.IF(this.I.U())&&!this.i.isManifestless},HOa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.lN(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.NMa.get(e);null==n&&(n=GOa[e]||GOa[e.replace(/-/g,"_")],g.NMa.set(e,n));h=n||h}c.push(new g.kG({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},IOa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},JOa=function(a,b,c){var d=
[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.lN(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},y4=function(a){if(!KOa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(LOa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},z4=function(a,b,c,d,e,f){var h={};
Object.assign(h,b);Object.assign(h,a.params);Object.assign(h,c);var l={};Object.assign(l,b.ld);a.params.ld&&Object.assign(l,a.params.ld);Object.assign(l,c.ld);h.ld=l;g.V.call(this,{G:"div",L:"caption-window",W:{id:"caption-window-"+a.id,dir:1===h.Kf?"rtl":"ltr",tabindex:"0",lang:h.lang},T:[{G:"span",L:"captions-text",W:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.ya=!1;this.u=a;this.Ca=this.Ba=null;this.playerWidth=e;this.playerHeight=f;this.J=null;this.maxWidth=.96*e;this.Ua=.96*
f;this.i=h;this.xb=c;this.Ha=b;this.C=this.Ga("captions-text");this.qb=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.Ma=d/360*16;this.type=0;this.Ya=this.Ma*MOa(l);a=new g.gy(this.element,!0);g.J(this,a);a.subscribe("dragstart",this.YO,this);a.subscribe("dragmove",this.XO,this);a.subscribe("dragend",this.WO,this);this.fb=this.eb=0;b="";this.i.windowOpacity&&(a=y4(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+
","+this.i.windowOpacity+")");a={"background-color":b,display:!1===this.i.isVisible?"none":"","text-align":NOa[this.i.textAlign]};this.qb&&(a["border-radius"]=b?this.Ya/8+"px":"");if(this.B=2===this.u.params.Kf||3===this.u.params.Kf)b=this.element,c="vertical-rl",1===this.i.zF&&(c="vertical-lr"),g.ke&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Ql(b,"-o-writing-mode",c),g.Ql(b,"-webkit-writing-mode",c),g.Ql(b,"writing-mode",c),g.Ql(b,"text-orientation","upright"),g.N(b,"ytp-vertical-caption"),3===this.u.params.Kf&&
(g.Ql(b,"text-orientation",""),g.Ql(b,"transform","rotate(180deg)"));g.Ql(this.element,a);switch(this.i.gi){case 0:case 1:case 2:g.N(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.N(this.element,"ytp-caption-window-bottom")}},MOa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},OOa=function(a,b){var c={},d=b.background?b.background:a.i.ld.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.ld.backgroundOpacity;d=y4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.qb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Ya/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ma*MOa(b)+"px";d=1;e=b.color||a.i.ld.color;if(b.color||null!=b.textOpacity)e=y4(e),d=null==b.textOpacity?a.i.ld.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.nC&&(h=e=b.nC);var l=a.Ma/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Kt()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.ld.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.rj&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.HR&&(c.visibility="hidden");1===b.OJ&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.MF||g.ij,3===a.u.params.Kf?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Jj||2===b.Jj||3===b.Jj||4===b.Jj||5===b.Jj)if(g.MF)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Jj){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},POa=function(a){a.J=g.wg("SPAN");
g.Ql(a.J,{display:"block"});g.N(a.J,"caption-visual-line");a.C.appendChild(a.J)},QOa=function(a,b){var c=g.wg("SPAN");
g.Ql(c,{display:"inline-block","white-space":"pre-wrap"});g.Ql(c,OOa(a,b));c.classList.add("ytp-caption-segment");a.J.appendChild(c);c.previousElementSibling&&(g.Ql(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Ql(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},ROa=function(a,b,c){a.ya=a.ya||!!c;
var d={};Object.assign(d,a.i.ld);Object.assign(d,c||b.i);Object.assign(d,a.xb.ld);(c=!a.J)&&POa(a);for(var e=a.Ba&&a.Ca&&g.Zb(d,a.Ca)?a.Ba:QOa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(POa(a),e=QOa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.xg(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.MF||!g.Tl(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Tl(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.rg?g.Ql(e,m,"1em"):g.Ql(e,m,"0.5em")))}a.Ca=d;a.Ba=e;a.D.push(b)},A4=function(a,b,c){g.jN.call(this,a);
this.videoData=b;this.audioTrack=c;this.C=b.OB},B4=function(a,b,c,d,e,f,h){z4.call(this,a,b,c,d,e,f,h);
this.type=1},C4=function(a,b,c,d,e,f,h){z4.call(this,a,b,c,d,e,f,h);
this.type=2;this.K=[];this.V=this.N=this.La=0;this.ma=NaN;this.ib=0;this.ub=null;this.Qa=new g.M(this.UU,433,this);g.N(this.element,"ytp-caption-window-rollup");g.J(this,this.Qa);g.Ql(this.element,"overflow","hidden")},SOa=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.zF&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},TOa=function(a){a.K=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.wm,c=0,d=0,e=a.K.length-1;c<b&&-1<e;){var f=a.K[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.K.length<b&&(d*=b/a.K.length);a.N=d;b=Math;c=b.max;isNaN(a.ma)&&((d=a.i.Um)?(e=g.wg("SPAN"),g.Dg(e,"\u2013".repeat(d)),g.Ql(e,OOa(a,a.i.ld)),a.C.appendChild(e),a.ma=e.offsetWidth,a.C.removeChild(e)):a.ma=0);d=a.C;a.V=c.call(b,a.ma,a.ib,(a.B?d.offsetHeight:d.offsetWidth)+1)},UOa=function(a,b){TOa(a);
var c=a.K.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.N-c;if(c!==a.La){var d=0<c&&0===a.La;b||isNaN(c)||d||(g.N(a.element,"ytp-rollup-mode"),g.Iq(a.Qa));g.Ql(a.C,"transform",SOa(a,c));a.La=c}TOa(a)},D4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.xA.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},E4=function(a,b,c,d,e){g.xA.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},VOa=function(a){var b="_"+F4++;
return new E4(0,0x8000000000000,0,b,a)},XOa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.ge){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=WOa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new D4(a,b,e,c,l,d,m)}switch(m.ge){case 9:case 10:m.Jj=1;break;case 11:m.Jj=2;break;case 12:m.Jj=3;break;case 13:m.Jj=4;break;case 14:m.Jj=5}return new D4(a,b,e,c,l.textContent||"",d,m)},WOa=function(a,b,c,d,e){var f=g.Kt(),h=
f?g.wg("DIV"):g.wg("RUBY"),l=g.wg("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.wg("DIV"):g.wg("RP");a.textContent=b;h.appendChild(a);b=f?g.wg("DIV"):g.wg("RT");b.textContent=c;h.appendChild(b);c=e.ge;if(10===c||11===c||12===c||13===c||14===c)if(g.Ql(b,"text-emphasis-style","filled circle"),g.Ql(b,"text-emphasis-color","currentcolor"),g.Ql(b,"webkit-text-emphasis","filled circle"),11===e.ge||13===e.ge)g.Ql(b,"webkit-text-emphasis-position","under left"),g.Ql(b,"text-emphasis-position","under left");c=!0;if(4===e.ge||7===e.ge||12===e.ge||
14===e.ge)g.Ql(h,"ruby-position","over"),g.Ql(h,"-webkit-ruby-position","before");else if(5===e.ge||6===e.ge||11===e.ge||13===e.ge)g.Ql(h,"ruby-position","under"),g.Ql(h,"-webkit-ruby-position","after"),c=!1;e=f?g.wg("DIV"):g.wg("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Ql(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Ql(f,"display","none"),f=f.nextElementSibling,g.Ql(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Ql(h.lastElementChild,"display","none"),d?(g.Ql(h,"padding-top","0.6em"),g.Ql(f,"top","0")):(g.Ql(h,"padding-bottom","0.6em"),g.Ql(f,"bottom","0")));return h},G4=function(){g.I.apply(this,arguments)},H4=function(a){G4.call(this);
this.D=a;this.C={};this.V={};this.ea={};this.J="_"+F4++;this.N={};this.B=this.i=null;this.K=!0},I4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},J4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},K4=function(a,b){a=I4(a,b);
return void 0!==a?a:null},M4=function(a,b){a=a.getAttribute(b);
if(null!=a)return L4.test(a),a},YOa=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.ea[d]:a.D);a=K4(b,"mh");null!=a&&(c.Bs=a);a=K4(b,"ju");null!=a&&(c.textAlign=a);a=K4(b,"pd");null!=a&&(c.Kf=a);a=K4(b,"sd");null!=a&&(c.zF=a);a=M4(b,"wfc");null!=a&&(c.windowColor=a);b=I4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},ZOa=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.V[d]);a=K4(b,"ap");null!=a&&(c.gi=a);a=I4(b,"cc");null!=a&&(c.Um=a);a=I4(b,"ah");null!=a&&(c.jh=a);a=I4(b,"rc");null!=a&&(c.wm=a);b=I4(b,"av");null!=b&&(c.Kj=b);return c},$Oa=function(a,b,c,d){var e={};
Object.assign(e,ZOa(a,b));Object.assign(e,YOa(a,b));d?g.Zb(e,a.D)?(d=a.J,e=a.D):d="_"+F4++:d=b.getAttribute("id")||"_"+F4++;a=I4(b,"t")+c;b=I4(b,"d")||0x8000000000000;if(2===e.Kf||3===e.Kf)c=e.wm,e.wm=e.Um,e.Um=c;return new E4(a,b,0,d,e)},N4=function(a){G4.call(this);
this.J=a;this.i=new Map;this.C=new Map;this.D=new Map;this.B=new Map},O4=function(a){a=g.Vf(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},aPa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.wm=a);b=b.ccColCount;void 0!==b&&(f.Um=b);if(2===f.Kf||3===f.Kf)b=f.wm,f.wm=f.Um,f.Um=b;return new E4(c,d,0,e,f)},Q4=function(){this.B=this.time=this.mode=this.u=0;
this.C=new P4(this);this.D=new P4(this);this.i=[];this.clear()},cPa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{ep:a,
Pm:b,result:0};a=bPa[a];b=bPa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Pm===d;if(d)return{ep:a,Pm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{ep:a,Pm:b,result:2};return{ep:a,Pm:b,result:3}},ePa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,dPa(a.C,b,c,d))},fPa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.r(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?ePa(a,d.pI,d.qI,b):1===d.type&&a.u&496&&dPa(a.D,d.pI,d.qI,b);a.i.length=0},R4=function(){this.type=0},S4=function(){this.state=this.Pm=this.ep=0},gPa=function(){this.timestamp=this.i=0},T4=function(a){this.D=a;
this.B=[];this.i=this.u=this.row=0;this.style=new R4;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new gPa}},U4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.i){0===c&&(c=m,d=p);n=String.fromCharCode(q.i);var t=q.timestamp;t<e&&(e=t);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.i,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===q)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},lPa=function(a,b){switch(a){case 0:return hPa[(b&127)-32];
case 1:return iPa[b&15];case 2:return jPa[b&31];case 3:return kPa[b&31]}return 0},V4=function(a){return a.B[a.row][a.u]},W4=function(a,b,c){2<=b&&1<a.u&&(--a.u,V4(a).i=0);
var d=V4(a);d.timestamp=a.D.time+0;d.i=lPa(b,c);32>a.u&&a.u++},mPa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},X4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},Y4=function(a){a.row=0<a.i?a.i:1;
a.u=1;X4(a,0,15)},Z4=function(a){this.B=a;
this.D=0;this.style=new R4;this.J=new T4(this.B);this.K=new T4(this.B);this.text=new T4(this.B);this.u=this.J;this.C=this.K;this.i=this.u},$4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(U4(d,c),Y4(a.u),Y4(a.C),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.i!==b&&(d.i>b?(U4(d,c),X4(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},nPa=function(a){a.style.set(1);
a.i=a.C;a.i.i=0;a.i.style=a.style;a.B.mode=1<<a.i.C},oPa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.B.mode=1<<a.i.C},P4=function(a){this.i=a;
this.D=0;this.B=new Z4(this.i);this.J=new Z4(this.i);this.u=new S4;this.C=this.B},dPa=function(a,b,c,d){a.u.update();
b=cPa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.ep;c=b.Pm;if(32<=e||!e)a.i.mode&a.i.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.i,b&96&&W4(a,0,b),c&96&&W4(a,0,c),0!==b&&0!==c&&3===a.style.type&&U4(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.ep=e,b.Pm=c,b.state=2,b=e&8?a.J:a.B,a.C=b,a.i.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.i.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;mPa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));X4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:W4(b.i,0,32);break a;case 48:57===c?(d=b.i,V4(d).i=0,32>d.u&&d.u++):W4(b.i,1,c&15)}break;case 2:c&32&&W4(b.i,2,c&31);break;case 3:c&32&&W4(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:nPa(b);
break;case 33:d=b.i;1<d.u&&(--d.u,V4(d).i=0);break;case 36:d=b.i;b=V4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:$4(b,2,d);break;case 38:$4(b,3,d);break;case 39:$4(b,4,d);break;case 40:W4(b.i,0,32);break;case 41:b.style.set(2);b.i=b.u;b.i.i=0;b.i.style=b.style;b.B.mode=1<<b.i.C;break;case 42:d=b.text;d.i=15;d.style.set(4);Y4(d);oPa(b);break;case 43:oPa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:U4(a,d)}X4(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;U4(a,d);mPa(a,b,b+1,a.i-1);X4(a,a.row,1)}break;case 46:X4(b.C,0,15);break;case 47:U4(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,nPa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.u+=c&3)&&(d.u=32)}}},pPa=function(){},a5=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.J=this.C=this.i=0;this.u=new DataView(this.trackData);this.B=[]},b5=function(a){var b=a.i;
a.i+=1;return a.u.getUint8(b)},c5=function(a){var b=a.i;
a.i+=4;return a.u.getUint32(b)},d5=function(a,b){G4.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.i=new Q4;this.i.u=1<<this.track},e5=function(a){if("string"===typeof a)return!1;
a=new a5(a,8,0);return qPa(a)},qPa=function(a){if(!(a.i<a.u.byteLength)||1380139777!==c5(a))return!1;
a.version=b5(a);if(1<a.version)return!1;b5(a);b5(a);b5(a);return!0},f5=function(){G4.call(this)},rPa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.rj=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new D4(b,c,d,e.id,p.nodeValue,f||0<n,g.Wb(l)?void 0:l),m.push(p),e.i.push(p);else{var q={};Object.assign(q,l);rPa(a,b,c,d,e,!0,p,q,m)}}},g5=function(a){var b=a.split(":");
a=0;b=g.r(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},sPa=function(a,b,c,d){d=Object.assign({Bs:0},d);
return new E4(a,b,c,"_"+F4++,d)},h5=function(a){g.I.call(this);
this.X=a;this.i=null},yPa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.X.Y("enable_h5_ssdai_caption")&&b){var f=e,h=tPa(b,d),l=[];try{for(var m=g.r(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,t=p.qF;l="string"!==typeof q?l.concat(uPa(a,c,q,t,f)):"WEBVTT"===q.substring(0,6)?l.concat(vPa(a,q,t)):l.concat(wPa(a,c,q,t))}var u=l}catch(x){g.rz(x),a.clear(),u=[]}if(0!==u.length)return u}a.X.Y("html5_disable_rawcc_killswitch")?"string"!==typeof b&&(u=new DataView(b),8<=u.byteLength&&1718909296===u.getUint32(4)&&(u=g.dC(u,0,1835295092),b=a.X.Y("html5_fix_mdat_offset_killswitch")?
b.slice(u.dataOffset,u.dataOffset+u.size):b.slice(u.dataOffset,u.offset+u.size),e5(b)||(b=g.Ya(new Uint8Array(b))))):b=xPa(a,b);if(!b)return[];try{return"string"!==typeof b?uPa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?vPa(a,b,d):wPa(a,c,b,d)}catch(x){return g.rz(x),a.clear(),[]}},xPa=function(a,b){if("string"===typeof b||e5(b))return b;
var c=new DataView(b);if(8>=c.byteLength||1718909296!==c.getUint32(4))return"";c=g.dC(c,0,1835295092);if(!c||!c.size)return"";a=a.X.Y("html5_fix_mdat_offset_killswitch")?b.slice(c.dataOffset,c.dataOffset+c.size):b.slice(c.dataOffset,c.offset+c.size);return g.Ya(new Uint8Array(a))},tPa=function(a,b){if("string"===typeof a||e5(a))return[{trackData:a,
qF:b}];var c=new DataView(a);if(8>=c.byteLength||1718909296!==c.getUint32(4))return[];var d=g.mC(c,1835295092);if(!d||!d.length||!d[0].size)return[];var e=[];d=g.r(d.entries());for(var f=d.next();!f.done;f=d.next()){var h=g.r(f.value);f=h.next().value;h=h.next().value;h=g.Ya(new Uint8Array(a.slice(h.dataOffset,h.offset+h.size)));e.push({trackData:h,qF:b+1E3*f})}zPa(c,e,b);return e=e.filter(function(l){return!!l.trackData})},zPa=function(a,b,c){var d=g.dC(a,0,1836476516),e=9E4;
d&&(e=g.eC(d)||9E4);d=0;var f=g.mC(a,1836019558);f=g.r(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.r(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.dC(a,l.dataOffset,1953653094))&&(l=g.dC(a,l.dataOffset,1952867444))&&(l=g.kC(l)/e*1E3,0===h&&(d=l),b[h].qF=l-d+c||c*h*1E3)}},uPa=function(a,b,c,d,e){if(!e5(c))throw Error("Invalid binary caption track data");
a.i||(a.i=new d5(e,b));return a.i.u(c,d)},vPa=function(a,b,c){a.i||(a.i=new f5);
a=a.i.u(b,c);.01>Math.random()&&g.sz(Error("Deprecated subtitles format in web player: WebVTT"));return a},wPa=function(a,b,c,d){if("{"===c[0])try{return a.i||(a.i=new N4(APa(b))),a.i.u(c,d)}catch(f){return g.rz(f),[]}var e=g.T1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.i||(a.i=new H4(APa(b),a.X)),a.i.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},APa=function(a){var b=
{};
if(a=g.nG(a))b.lang=a,g.iLa.test(a)&&(b.Kf=1);return b},k5=function(a){g.gN.call(this,a);
var b=this;this.I=a;this.X=this.I.U();this.videoData=this.I.getVideoData();this.sb=this.I.gb();this.C={ld:{}};this.D={ld:{}};this.ya=[];this.N={};this.Ma={};this.ea=!1;this.ub=g.yH(this.videoData);this.eb=g.nua(this.videoData,this.I);this.qb=!!this.videoData.captionTracks.length;this.xb=!!this.videoData.Yb;this.La="3"===this.X.controlsType;this.u=this.J=this.K=this.Ha=this.Ya=null;this.Qa=new h5(this.X);this.i=null;this.ma=new g.ID(this);this.Ua=new g.V({G:"div",L:"ytp-caption-window-container",W:{id:"ytp-caption-window-container"}});
var c=null,d=g.yr("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.ir(d));this.storage=c;c=a.hd();this.fb=!(null===c||void 0===c||!c.Rw());this.B=BPa(this);this.V=!this.B&&this.La&&this.fb&&this.eb;g.J(this,this.Qa);this.B?this.Ca=this.Ba=null:(this.Ba=new g.Eq(this.QF,void 0,this),g.J(this,this.Ba),this.Ca=new g.M(this.gW,2E3,this),g.J(this,this.Ca));g.J(this,this.ma);this.X.Y("caption_window_container_killswitch")||g.XM(this.player,this.Ua.element,4);g.J(this,this.Ua);this.B||this.ma.S(a,
"resize",this.SF);(this.ib=!g.Wx()&&!this.I.isFullscreen()&&!this.B&&!this.V&&!this.X.Y("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.ma.S(a,"resize",this.ZT);this.ma.S(a,"onPlaybackAudioChange",this.aT);this.ma.S(a,g.AA("captions"),function(e){b.Fd(e)});
this.ma.S(a,g.BA("captions"),function(e){b.uf(e)});
i5(this,j5(this,"display-settings")||{})},DPa=function(a){if(1===a.X.Ua||1===a.videoData.Wt||"alwayson"===g.hH(a.videoData,"yt:cc"))return!0;
if(2===a.X.Ua){var b;g.KF(a.X)?b=CPa(a):b=j5(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().u;b=t4(a.player.getAudioTrack(),u4(a.X));var d=g.hH(a.videoData,"yt:cc");if(void 0===l5(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===b)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===b)return"on"===d}else return"on"===d;return"ON"===c||"on"===g.hH(a.videoData,"yt:cc")},m5=function(a,b){if(a.i&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.i||"FORCED_ON"===a.u},l5=function(a){var b=void 0,c=g.xv(g.vv.getInstance(),65);
if(g.KF(a.X)&&null!=c){if(null!=CPa(a))return!1;b=!c}return b},EPa=function(a){var b;
a.ub?b=new A4(a.X,a.videoData,a.player.getAudioTrack(),a.player):a.eb?b=new x4(a.videoData.i,a.player):a.qb?b=new g.kN(a.X,a.videoData,a.player.getAudioTrack()):b=new g.mN(a.X,a.videoData.Yb,a.videoData.videoId,g.Soa(a.videoData),a.videoData.Rj);return b},o5=function(a,b){if(a.u){if(a.J&&a.J.C)return a.J.C;
b||(b=a.xb?!1:a.qb?!1:!0);b=g.hN(a.u.u,b);for(var c=[a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.hH(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.nG(b[e])===c[d])return b[e];return a.J&&a.J.B?a.J.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||n5(a)}return null},n5=function(a){return a.J&&a.J.i},p5=function(a){var b=n5(a);
return!!b&&a.i===b},FPa=function(a){var b=t4(a.player.getAudioTrack(),u4(a.X)),c;
"CAPTIONS_INITIAL_STATE_UNKNOWN"===b?l5(a)||a.ea||DPa(a)?c=o5(a,a.ea):m5(a)&&(c=n5(a)):"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=o5(a,a.ea):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&m5(a)&&(c=n5(a));if(a.B||a.V){var d=g.hN(a.u.u,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.wg("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.lG(f));h.setAttribute("srclang",g.nG(f));h.setAttribute("id",f.toString());a.V||h.setAttribute("src",a.u.Fp(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.I.hd();c.tu(b);c=c.Le();a.fb&&a.ma.S(c.textTracks,"change",a.AV)}else!a.i&&c&&q5(a,c),a.player.Na("onCaptionsTrackListChanged"),a.player.Na("onApiChange")},GPa=function(a,b){var c=a.I.hd().Le().textTracks;
a=a.i.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},q5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ea=c,a.ea&&(g.KF(a.X)?r5(a,!!b):s5(a,"module-enabled",!!b)));a.i=b;m5(a)&&(a.i=n5(a));a.load()},HPa=function(a,b){a.X.Y("caption_window_container_killswitch")?g.XM(a.player,b,4):a.Ua.element.appendChild(b)},IPa=function(a,b){var c=a.sb.getVideoContentRect(!0).height;
if(!c)return null;var d=a.i?g.nG(a.i):null;d&&g.iLa.test(d)&&(b.params.Kf=1);d=a.sb.getPlayerSize();switch(null!=b.params.Bs?b.params.Bs:1<b.i.length?1:0){case 1:return new B4(b,a.C,a.D,c,d.width,d.height,a.X.experiments);case 2:return new C4(b,a.C,a.D,c,d.width,d.height,a.X.experiments);default:return new z4(b,a.C,a.D,c,d.width,d.height,a.X.experiments)}},i5=function(a,b,c){c=void 0===c?!1:c;
var d=t5.ld;a.C={};Object.assign(a.C,t5);a.C.ld={};Object.assign(a.C.ld,d);a.D={ld:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;L4.test(f);e.ld.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;L4.test(f);e.ld.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||t5.windowColor;L4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.ld.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.ld.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.rj?3:d.bold?1:d.rj?2:0);f=f.ld;switch(e){case 1:f.bold=!0;delete f.rj;break;case 2:delete f.bold;f.rj=!0;break;case 3:f.bold=!0;f.rj=!0;break;default:delete f.bold,delete f.rj}e=b.textOpacityOverride?a.D:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.ld.textOpacity=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=t5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.ld.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.ld.fontFamily=f;a.loaded&&a.SF();c&&s5(a,"display-settings",b)},u5=function(a,b,c){b&&!a.K?(b=VOa({Kf:0,
lang:"en"}),a.K=[b,new D4(b.start,b.end-b.start,0,b.id,null!==c&&void 0!==c?c:"Captions look like this")],a.player.Md(a.K)):!b&&a.K&&(JPa(a,a.K),a.K=null)},JPa=function(a,b){a.player.dg(b);
g.Cb(b,function(c){g.ob(this.ya,c)},a);
g.Fq(a.Ba)},j5=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},s5=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},r5=function(a,b){a.I.isInline()||g.Mz("yt-player-sticky-caption",b,2592E3)},CPa=function(a){if(!a.I.isInline())return g.Nz("yt-player-sticky-caption")},BPa=function(a){var b=a.I.hd();
b=!(null===b||void 0===b||!b.Qw());return a.La&&b&&!a.eb};
g.NS.prototype.bv=g.ca(31,function(a){var b=2;this.ma.has(a)?b=0:g.Tza(this,a)&&(b=1);return b});
g.TV.prototype.bv=g.ca(30,function(a){return this.Id.bv(a)});
g.AN.prototype.Ar=g.ca(29,function(){this.ra();for(var a=g.jg(document,"track",void 0,this.i),b=0;b<a.length;b++)g.Ag(a[b])});
g.vS.prototype.Ar=g.ca(28,function(){this.va.Ar()});
g.AN.prototype.Rw=g.ca(27,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.vS.prototype.Rw=g.ca(26,function(){return this.va.Rw()});
g.AN.prototype.Qw=g.ca(25,function(){return!!this.i.textTracks});
g.vS.prototype.Qw=g.ca(24,function(){return this.va.Qw()});
g.AN.prototype.tu=g.ca(23,function(a){this.ra();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.vS.prototype.tu=g.ca(22,function(a){this.va.tu(a)});
g.jN.prototype.LE=g.ca(21,function(){return!1});
g.jN.prototype.Mn=g.ca(20,function(){});
g.kN.prototype.Mn=g.ca(19,function(a,b,c){var d=this;this.isDisposed();b=this.Fp(a,b);this.Cm();this.i=g.ot(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.mN.prototype.Mn=g.ca(18,function(a,b,c){var d=this;this.isDisposed();b=this.Fp(a,b);this.Cm();this.i=g.ot(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.CV.prototype.zv=g.ca(6,function(){return this.K});
g.ZX.prototype.zv=g.ca(5,function(){var a;return(null===(a=g.ZM(this))||void 0===a?void 0:a.uv())||null});
g.QM.prototype.uv=g.ca(4,function(){return this.app.zv()});
g.CX.prototype.uv=g.ca(3,function(){var a;return(null===(a=this.bb)||void 0===a?void 0:a.zv())||null});
var GOa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",ale:"Aleut",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",arp:"Arapaho",ars:"Najdi Arabic",arw:"Arawak",as:"Assamese",asa:"Asu",ast:"Asturian",av:"Avaric",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",
az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bas:"Basaa",bax:"Bamun",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bez:"Bena",bfd:"Bafut",bg:"Bulgarian",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",br:"Breton",bra:"Braj",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",
car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cr:"Cree",crh:"Crimean Turkish",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",
de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",
es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",
gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",
iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kha:"Khasi",
kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",
lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",
mi:"Maori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian (Moldova)",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",
ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",
pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",
sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",
sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",
syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",
umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};v4.prototype.contains=function(a){a=g.xb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
v4.prototype.length=function(){return this.segments.length/2};
g.w(w4,g.I);g.k=w4.prototype;g.k.Aa=function(){g.I.prototype.Aa.call(this);this.B&&this.B.cancel()};
g.k.FG=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Sc();var b=this.i;this.i=g.cb(this.ea.Ol(a).i);b!==this.i&&this.V&&this.V()};
g.k.reset=function(){this.C=new v4;this.J=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.xK=function(){var a;this.isDisposed();var b;if(b=null!=this.i)b=this.i,b=b.i.Hm(b);if(b&&!this.B&&!(this.i&&30<this.i.startTime-this.player.getCurrentTime())){b=this.i;b=b.i.It(b);if(this.X.Y("enable_h5_ssdai_caption")&&(null===(a=this.player.getVideoData())||void 0===a?0:a.enableServerStitchedDai)){var c=this.player.uv();if(c){var d=b.i[0].Oa,e=c.Nr(b.i[0].C,d,b.i[0].i.info.id,3);if(e)if(c=c.bv(d),0===c)e&&(b.B=new g.IB(e));else if(2===c){this.K.start();EOa(this)&&this.seekTo(this.player.getCurrentTime());
return}}}b.i[0].duration?(this.C.contains(b.i[0].Oa)||FOa(this,b),this.i=g.cb(b.i)):!this.X.experiments.oa("force_caption_seek_for_live_killswitch")&&EOa(this)&&this.seekTo(this.player.getCurrentTime())}this.K.start()};
g.k.ra=function(){};
g.w(x4,g.jN);g.k=x4.prototype;g.k.Mn=function(a,b,c){var d=this;this.Cm();b=IOa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?JOa(this,b,"386"):JOa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.lua(this.X);this.B=new w4(f,this.I,b,function(h,l){c(h,a,l,e)},this.J||g.rD(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.LE=function(){var a=this.D;this.D=!1;return a};
g.k.xs=function(a){var b=this.J?[new g.kG({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.kG({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?HOa(this,"386"):HOa(this);b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.iN(this.u,c.value);a()};
g.k.Cm=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Fp=function(){return""};
var L4=/^#(?:[0-9a-f]{3}){1,2}$/i,LOa=/#(.)(.)(.)/,KOa=/^#(?:[0-9a-f]{3}){1,2}$/i;var NOa=["left","right","center","justify"];g.w(z4,g.V);g.k=z4.prototype;g.k.YO=function(a,b){var c=g.cm(this.element,this.element.parentElement);this.eb=a-c.x;this.fb=b-c.y;g.N(this.element,"ytp-dragging")};
g.k.XO=function(a,b){var c=g.em(this.element);a=a-this.eb-.02*this.playerWidth;var d=b-this.fb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Vf(e,0,2));var f=(d+c.height/2)/this.Ua*3;f=Math.floor(g.Vf(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Vf(a,0,1);c=(d+f/2*c.height)/this.Ua;c=100*g.Vf(c,0,1);this.u.params.gi=b;this.u.params.Kj=c;this.u.params.jh=a;this.i.gi=b;this.i.Kj=c;this.i.jh=a;this.Ha.gi=b;this.Ha.Kj=c;this.Ha.jh=a;this.tM()};
g.k.WO=function(){g.Qq(this.element,"ytp-dragging")};
g.k.tM=function(){this.Vs(this.D)};
g.k.Pb=function(){return this.type};
g.k.Vs=function(a){var b=Math.min(this.oJ(),this.maxWidth),c=this.nJ(),d="";3===this.u.params.Kf&&(d="rotate(180deg)");g.Ql(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.YB(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.jh+2;d=this.i.gi;switch(d){case 0:case 3:case 6:(b=this.i.ld.fontSizeIncrement)&&0<b&&2!==this.i.Kf&&3!==
this.i.Kf&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.Kj+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Ql(this.element,
a)};
g.k.YB=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.ya||this.D.length>b)b=0,this.ya=!1,this.D=[],this.J=this.Ca=this.Ba=null,g.yg(this.C);for(;b<a.length;b++)ROa(this,a[b])};
g.k.oJ=function(){return 0};
g.k.nJ=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.w(A4,g.jN);A4.prototype.Mn=function(a,b,c){COa(this.videoData.videoId,a.vssId,c)};
A4.prototype.xs=function(a){if(this.audioTrack)for(var b=g.r(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.iN(this.u,c.value);a()};g.w(B4,z4);B4.prototype.YB=function(a){var b=this.u.i;z4.prototype.YB.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};Object.assign(d,c.i);Object.assign(d,KPa);var e=c.i;var f=d}ROa(this,c,d)}};
var KPa={HR:!0};g.w(C4,z4);g.k=C4.prototype;g.k.tM=function(){g.Jq(this.Qa)};
g.k.UU=function(){g.Qq(this.element,"ytp-rollup-mode");this.Vs(this.ub,!0)};
g.k.nJ=function(){return this.B?this.V:this.N};
g.k.oJ=function(){return this.B?this.N:this.V};
g.k.Vs=function(a,b){this.ub=a;if(this.u.params.wm){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.ib=this.V;this.N=this.V=0;z4.prototype.Vs.call(this,a);UOa(this,b)}z4.prototype.Vs.call(this,a)};g.w(D4,g.xA);D4.prototype.toString=function(){return g.xA.prototype.toString.call(this)};g.w(E4,g.xA);E4.prototype.toString=function(){return g.xA.prototype.toString.call(this)};
var F4=0;g.w(G4,g.I);G4.prototype.u=function(){return[]};
G4.prototype.reset=function(){};g.w(H4,G4);H4.prototype.reset=function(){this.N={};this.B=this.i=null;this.K=!0};
H4.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.r(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.r(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.C,h={},l=a.getAttribute("p");l&&Object.assign(h,this.C[l]);l=J4(a,"b");null!=
l&&(h.bold=l);l=J4(a,"i");null!=l&&(h.rj=l);l=J4(a,"u");null!=l&&(h.underline=l);l=K4(a,"et");null!=l&&(h.charEdgeStyle=l);l=K4(a,"of");null!=l&&(h.offset=l);l=M4(a,"bc");null!=l&&(h.background=l);l=M4(a,"ec");null!=l&&(h.nC=l);l=M4(a,"fc");null!=l&&(h.color=l);l=K4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=I4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=I4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=I4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=K4(a,"rb");null!=l&&10!==l&&0!==l&&(h.ge=
10<l?l-1:l);a=K4(a,"hg");null!=a&&(h.OJ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.ea[c]=YOa(this,a);break;case "wp":c=a.getAttribute("id"),this.V[c]=ZOa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.r(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.i=$Oa(this,a,b,!1);(a=this.N[this.i.id])&&a.end>this.i.start&&(a.end=this.i.start);this.N[this.i.id]=this.i;d.push(this.i);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.J;h=!!J4(a,"a");
l=(I4(a,"t")||0)+l;var m=I4(a,"d")||5E3;h||(!this.K&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.C[p]:null;var q=Array.from(a.childNodes);q.length&&(this.K=null!=a.getAttribute("d"));for(var t=0;t<q.length;t++){var u=q[t],x=void 0;0<t&&(h=!0);var y=void 0;1===u.nodeType&&(y=u);if(y&&"s"===y.tagName){if((u=(u=y.getAttribute("p"))?this.C[u]:null)&&u.ge&&(1===u.ge?(u=q.slice(t,t+4),4===u.length&&(x=
XOa(l,m,f,h,n,u,this.C),t+=3)):x=XOa(l,m,f,h,n,[y],this.C)),!x){var A=y;x=l;y=m;u=f;var D=h,F=n,H=A.textContent?A.textContent:"",K=A.getAttribute("p");K=K?this.C[K]:null;A=I4(A,"t")||0;x=new D4(x+A,y-A,F,u,H,D,K)}}else x=new D4(l,m,n,f,u.textContent||"",h,p);c.push(x);this.B=x}if(0<c.length)for(c[0].windowId===this.J&&(this.i=$Oa(this,a,b,!0),d.push(this.i)),a=g.r(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.i.id,this.i.i.push(c),d.push(c)}b=d}else b=[];return b};var LPa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(N4,G4);N4.prototype.reset=function(){this.B.clear()};
N4.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.r(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.i.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.rj=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.nC=O4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=O4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=O4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.ge=10<h?h-1:h,f.Jj=LPa.get(f.ge));e.hgHorizGroup&&(f.OJ=e.hgHorizGroup);this.i.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.r(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.J),void 0!==e.mhModeHint&&(f.Bs=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Kf=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.zF=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=O4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.r(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.jh=e.ahHorPos),void 0!==e.apPoint&&(f.gi=e.apPoint),void 0!==e.avVerPos&&(f.Kj=e.avVerPos),void 0!==e.ccCols&&(f.Um=e.ccCols),void 0!==e.rcRows&&(f.wm=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.r(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=aPa(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+F4++,h=aPa(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.i.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],u=t.utf8;if(u){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.i.get(t.pPenId));if(2===(null!=h.params.Bs?h.params.Bs:1<h.i.length?1:0)&&m&&"\n"===u)continue;if(t=y&&1===y.ge)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var A=p[t+1].pPenId;(A=this.i.get(A))&&A.ge&&2===A.ge?(A=p[t+2].pPenId,A=this.i.get(A),!A||!A.ge||3>A.ge?t=!1:(A=p[t+3].pPenId,t=(A=this.i.get(A))&&
A.ge&&2===A.ge?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;A=p[l+2].utf8;var D=this.i.get(p[l+2].pPenId);u=WOa(u,x,A,t,D);m=new D4(d,e,n,f,u,m,y);l+=3}else m=new D4(d+x,e-x,n,h.id,u,m,y||q);m&&(a.push(m),h.i.push(m))}m=!0}}}b=a}else b=[];return b};Q4.prototype.clear=function(){this.B=this.time=this.mode=0;this.i=[];this.reset()};
Q4.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var bPa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];R4.prototype.set=function(a){this.type=a};
R4.prototype.get=function(){return this.type};
S4.prototype.clear=function(){this.state=0};
S4.prototype.update=function(){this.state=2===this.state?1:0};
S4.prototype.isValid=function(){return 0!==this.state};
S4.prototype.matches=function(a,b){return this.isValid()&&a===this.ep&&b===this.Pm};
gPa.prototype.reset=function(){this.timestamp=this.i=0};
T4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
T4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
T4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.i=0;this.u=this.row=1};
var hPa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],iPa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],jPa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],kPa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Z4.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.J;this.C=this.K;this.i=this.u;var c=(a<<2)+(b<<1);this.J.reset(c);this.K.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
P4.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.J.reset(a,1)};pPa.prototype.D=function(){};g.w(a5,pPa);a5.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+F4++;c=c/1E3-this.K;d=d/1E3-this.K;a=new E4(c,d-c,5,f,{textAlign:0,gi:0,jh:2.5*b,Kj:5.33*a});e=new D4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.w(d5,G4);d5.prototype.u=function(a){a=new a5(a,a.byteLength,this.B);if(qPa(a)){for(;a.i<a.u.byteLength;)for(0===a.version?a.C=c5(a)*(1E3/45):1===a.version&&(a.C=4294967296*c5(a)+c5(a)),a.J=b5(a);0<a.J;a.J--){var b=b5(a),c=b5(a),d=b5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.C,type:this.track,pI:c,qI:d,order:b.i.length}))}fPa(this.i,a);return a.B}return[]};
d5.prototype.reset=function(){this.i.clear()};g.w(f5,G4);
f5.prototype.u=function(a,b){var c=[];a=a.split(MPa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!NPa.test(e)){var h=v5.exec(e);if(h&&4<=h.length){var l=g5(h[1]),m=g5(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var t=null,u="";n=g.r(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],h.Kj=Number.parseInt(p,10),2===x.length&&(q=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];h.jh=Number.parseInt(t,10);2===x.length&&(u=x[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!t)switch(h.textAlign){case 0:h.jh=0;break;case 1:h.jh=100;break;case 2:h.jh=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.gi=q}e=e.substring(v5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=sPa(l,m,5,u),m=new D4(l,m,5,f.id,h,!1,g.Wb(e)?void 0:e),c.push(f),c.push(m),f.i.push(m);else for(q=h.split(OPa),1===q.length?(h=5,u=sPa(l,m,h,u)):(p=h=6,u=Object.assign({Um:32},u),u=new E4(l,m,p,"_"+F4++,u)),c.push(u),p=l,t=0;t<q.length;t++)n=q[t],0===t%2?(x=g.T1("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,rPa(this,p,m-(p-l),h,u,0<t,y,e,c)):p=g5(n)+f}v5.lastIndex=0}}return c};
var NPa=/^NOTE/,MPa=/(?:\r\n|\r|\n){2,}/,v5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),OPa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.CS.Py(f5,{u:"wvppt"});g.w(h5,g.I);h5.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
h5.prototype.reset=function(){this.i&&this.i.reset()};
h5.prototype.Aa=function(){g.I.prototype.Aa.call(this);this.clear()};var t5={windowColor:"#080808",windowOpacity:0,textAlign:2,gi:7,jh:50,Kj:100,ld:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(k5,g.gN);g.k=k5.prototype;g.k.Aa=function(){if(this.B||this.V){var a=this.I.hd();a&&!a.isDisposed()&&a.Ar()}else u5(this,!1);g.gN.prototype.Aa.call(this)};
g.k.xq=function(){if(this.La)return this.B||this.V;var a=t4(this.player.getAudioTrack(),u4(this.X));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?m5(this):l5(this)||m5(this)?!0:DPa(this)};
g.k.load=function(){var a=this;g.gN.prototype.load.call(this);var b=!this.X.experiments.oa("web_player_captions_track_list_changed_killswitch");this.J=this.player.getAudioTrack();this.u?(this.i&&(this.Qa.clear(),this.B?GPa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Mn(this.i,"json3",function(c,d,e,f){c&&(a.u.LE()&&(a.ya=[],a.I.bf("captions"),g.Fq(a.Ba),a.Qa.reset()),c=yPa(a.Qa,c,d,e,f),a.player.Md(c),!a.ea||a.V||p5(a)||g.wF(a.X)||g.pF(a.X)||(g.Kq(a.Ca),c=VOa({gi:0,jh:5,Kj:5,wm:2,textAlign:0,
Kf:0,lang:"en"}),a.Ha=[c],d=["Click "," for settings"],a.Ya||(e=new g.YK(g.nL()),g.J(a,e),a.Ya=e.element),e=c.end-c.start,(f=g.lG(a.i))&&a.Ha.push(new D4(c.start,e,0,c.id,f)),a.Ha.push(new D4(c.start,e,0,c.id,d[0]),new D4(c.start,e,0,c.id,a.Ya,!0),new D4(c.start,e,0,c.id,d[1],!0)),a.player.Md(a.Ha),g.Iq(a.Ca)),!a.ea||a.V||p5(a)||(g.KF(a.X)?r5(a,!0):s5(a,"module-enabled",!0),a.J&&(a.J.C=a.i),a.player.Fq()),a.ea=!1)}),!b||this.B||this.V||p5(this)||this.player.Na("captionschanged",g.mG(this.i))),b||
(this.i&&!p5(this)?this.player.Na("captionschanged",g.mG(this.i)):this.player.Na("onCaptionsTrackListChanged"))):(this.u=EPa(this),g.J(this,this.u),this.u.xs(function(){FPa(a)}))};
g.k.unload=function(){this.B&&this.i?GPa(this,!1):(this.Ca&&g.Kq(this.Ca),this.player.bf("captions"),this.ya=[],this.u&&this.u.Cm(),this.Qa.clear(),this.K&&this.player.Md(this.K),this.SF());g.gN.prototype.unload.call(this);this.player.Fq();this.player.Na("captionschanged",{})};
g.k.create=function(){this.xq()&&this.load()};
g.k.AV=function(){for(var a=this.I.hd().Le().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=g.hN(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.i:null)!==b&&q5(this,b,!0)};
g.k.cX=function(){!this.i&&this.B||this.unload()};
g.k.Fd=function(a){this.ya.push(a);g.Fq(this.Ba)};
g.k.uf=function(a){g.ob(this.ya,a);this.u instanceof x4&&this.u.J&&this.player.dg([a]);g.Fq(this.Ba)};
g.k.aW=function(a){if(a instanceof E4){var b=this.N[a.id];b&&b.u!==a&&(b.dispose(),delete this.N[a.id],b=null);b||(b=IPa(this,a))&&(this.N[a.id]=b)}else b=a.windowId,this.Ma[b]||(this.Ma[b]=[]),this.Ma[b].push(a)};
g.k.getCaptionWindowContainerId=function(){return this.Ua.element.id};
g.k.gW=function(){JPa(this,this.Ha);this.Ha=null};
g.k.QF=function(){var a=this;if(!this.ib||!this.B){this.Ba.stop();g.Xb(this.Ma);this.ya.sort(g.zA);var b=this.ya;if(this.K){var c=g.Io(b,function(d){return-1===this.K.indexOf(d)},this);
c.length&&(b=c)}g.Cb(b,this.aW,this);g.Fb(this.N,function(d,e){a.Ma[e]?(d.element.parentNode||(d instanceof C4||d instanceof B4||g.Ib(a.N,function(f,h){h!==e&&f.u.params.gi===d.u.params.gi&&f.u.params.jh===d.u.params.jh&&f.u.params.Kj===d.u.params.Kj&&(f.dispose(),delete a.N[h]);return h===e},a),HPa(a,d.element)),d.Vs(a.Ma[e])):(d.dispose(),delete a.N[e])},this)}};
g.k.kW=function(){i5(this,{},!0);this.X.experiments.oa("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Na("captionssettingschanged")};
g.k.dR=function(){var a=t5.ld;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.rj?3:a.bold?1:a.rj?2:0,textOpacity:a.textOpacity,windowColor:t5.windowColor,windowOpacity:t5.windowOpacity};var b=j5(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.sN=function(a,b){var c={};Object.assign(c,j5(this,"display-settings"));Object.assign(c,a);i5(this,c,b);this.player.Na("captionssettingschanged")};
g.k.SF=function(){!this.B&&this.loaded&&(g.Fb(this.N,function(a,b){a.dispose();delete this.N[b]},this),this.QF())};
g.k.gf=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Vf(b,-2,4);this.sN({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&q5(this,this.i,!0);break;case "stickyLoading":void 0!==b&&this.X.B&&(g.KF(this.X)?r5(this,!!b):s5(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.La(b))break;if(g.Wb(b)){q5(this,null,!0);break}a=g.hN(this.u.u,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?BOa(e,b.translationLanguage):e)}!c||c===this.i&&this.loaded||(b=g.ema(),a=g.nG(c),b.length&&a===b[b.length-1]||(b.push(a),g.Mz("yt-player-caption-language-preferences",b)),q5(this,c,!0))}else return this.loaded&&this.i&&!p5(this)?g.mG(this.i):{};return"";case "tracklist":return this.u?g.wm(g.hN(this.u.u,!(!b||!b.includeAsr)),function(f){return g.mG(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.B||void 0===b||u5(this,!!b);break;case "sampleSubtitlesCustomized":this.B||u5(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.X.B&&a.push("stickyLoading");return a};
g.k.iD=function(){var a=this.i;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.X.Y("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.nG(a));return{cc:b}}return{}};
g.k.RW=function(){this.loaded&&this.i&&!p5(this)?(g.KF(this.X)?r5(this,!1):s5(this,"module-enabled",!1),this.unload(),m5(this,!0)&&q5(this,n5(this),!1)):this.bN()};
g.k.bN=function(){this.loaded&&this.i&&!p5(this)||q5(this,p5(this)||!this.i?o5(this,!0):this.i,!0)};
g.k.aT=function(){var a=p5(this);m5(this,a)?q5(this,this.player.getAudioTrack().i,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.xq()&&(a?q5(this,o5(this),!1):this.load()))};
g.k.ZT=function(){var a=this.I.hd();a&&!a.isDisposed()&&a.Ar();this.I.isFullscreen()?(this.B=this.La=!0,this.loaded&&FPa(this)):(this.La="3"===this.X.controlsType,this.B=BPa(this));q5(this,this.i)};
g.CS.Py(k5,{QF:"smucd"});g.rN.captions=k5;})(_yt_player);
