(function(g){var window=this;'use strict';var UPa=function(a,b){a.Na("onAutonavCoundownStarted",b)},J5=function(a,b,c){g.O(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Ge(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.bG&&(b.lengthText?(e=b.lengthText||null,f=b.Up||null):b.lengthSeconds&&(e=g.XL(b.lengthSeconds),f=g.XL(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.YF(d).type;var l=b instanceof g.bG?b.isLivePlayback:null,m=b instanceof g.bG?b.isUpcoming:null;c={title:b.title,author:b.author,author_and_views:b.shortViewCount?b.author+" \u2022 "+b.shortViewCount:b.author,aria_label:b.zl||g.BI("Watch $TITLE",{TITLE:b.title}),duration:e,
timestamp:f,url:b.Ck(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:b.shortViewCount?b.shortViewCount+" \u2022 "+b.publishedTimeText:b.publishedTimeText,autoplayAlternativeHeader:b.Om};b instanceof g.aG&&(c.playlist_length=b.playlistLength);a.update(c)},K5=function(a){var b=a.U(),c=b.u;
g.V.call(this,{G:"a",L:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.K:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},T:[{G:"div",Ia:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},T:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ia:["ytp-autonav-timestamp"],xa:"{{duration}}"},{G:"div",Ia:["ytp-autonav-live-stamp"],xa:"Live"},{G:"div",
Ia:["ytp-autonav-upcoming-stamp"],xa:"Upcoming"},{G:"div",L:"ytp-autonav-list-overlay",T:[{G:"div",L:"ytp-autonav-mix-text",xa:"Mix"},{G:"div",L:"ytp-autonav-mix-icon"}]}]},{G:"div",Ia:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],xa:"{{title}}"},{G:"div",Ia:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],xa:"{{author}}"},{G:"div",Ia:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],xa:"{{views_and_publish_time}}"}]});this.I=a;this.suggestion=
null;this.i=c;this.Sa("click",this.onClick);this.Sa("keypress",this.u)},M5=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{G:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.D=b;this.u=0;b=a.U();var d=b.u;this.I=a;this.suggestion=null;this.i=new g.V({G:"div",L:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},T:[{G:"div",L:"ytp-autonav-endscreen-upnext-header"},{G:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",xa:"{{autoplayAlternativeHeader}}"},
{G:"a",L:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.K:""},T:[{G:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},T:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ia:["ytp-autonav-timestamp"],xa:"{{duration}}"},{G:"div",Ia:["ytp-autonav-live-stamp"],xa:"Live"},{G:"div",Ia:["ytp-autonav-upcoming-stamp"],xa:"Upcoming"}]},{G:"div",L:"ytp-autonav-endscreen-video-info",T:[{G:"div",L:"ytp-autonav-endscreen-premium-badge"},{G:"div",L:"ytp-autonav-endscreen-upnext-title",
xa:"{{title}}"},{G:"div",L:"ytp-autonav-endscreen-upnext-author",xa:"{{author}}"},{G:"div",L:"ytp-autonav-view-and-date",xa:"{{views_and_publish_time}}"},{G:"div",L:"ytp-autonav-author-and-view",xa:"{{author_and_views}}"}]}]}]});g.J(this,this.i);this.i.Fa(this.element);d||this.S(this.i.Ga("ytp-autonav-endscreen-link-container"),"click",this.TG);this.I.Vb(this.element,this,115127);this.I.Vb(this.i.Ga("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({G:"div",L:"ytp-autonav-overlay"});
g.J(this,this.overlay);this.overlay.Fa(this.element);this.B=new g.V({G:"div",L:"ytp-autonav-endscreen-button-container"});g.J(this,this.B);this.B.Fa(this.element);this.cancelButton=new g.V({G:"button",Ia:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],W:{"aria-label":"Cancel autoplay"},xa:"Cancel"});g.J(this,this.cancelButton);this.cancelButton.Fa(this.B.element);this.cancelButton.Sa("click",this.eP,this);this.I.Vb(this.cancelButton.element,this,115129);this.playButton=
new g.V({G:"a",Ia:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},xa:"Play Now"});g.J(this,this.playButton);this.playButton.Fa(this.B.element);this.playButton.Sa("click",this.TG,this);this.I.Vb(this.playButton.element,this,115130);this.C=new g.M(function(){L5(c)},500);
g.J(this,this.C);this.SG();this.S(a,"autonavvisibility",this.SG)},P5=function(a){var b=a.I.jj(!0,a.I.isFullscreen());
g.O(a.element,"ytp-autonav-endscreen-small-mode",a.qf(b));g.O(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.oA);g.O(a.I.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.I.Wd());g.O(a.I.getRootNode(),"countdown-running",a.Mh());g.O(a.element,"ytp-player-content",a.I.Wd());g.Ql(a.overlay.element,{width:b.width+"px"});if(!a.Mh()){a.I.Wd()?N5(a,Math.round(O5(a)/1E3)):N5(a);b=!!a.suggestion&&!!a.suggestion.Om;var c=a.I.Wd()||!b;g.O(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.O(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.aL(a.B,a.I.Wd())}},L5=function(a){var b=O5(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);N5(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Mh()?a.select(!0):a.Mh()&&a.C.start()},O5=function(a){var b=a.I.xp();
return 0<=b?b:g.T(a.I.U().experiments,"autoplay_time")||1E4},N5=function(a,b){b=void 0===b?-1:b;
a=a.i.Ga("ytp-autonav-endscreen-upnext-header");g.yg(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.xg("Up next in $SECONDS".slice(0,d)));var e=g.wg("span");g.Nq(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Dg(e,b);a.appendChild(e);a.appendChild(g.xg("Up next in $SECONDS".slice(d+c.length)));return}}g.Dg(a,"Up next")},Q5=function(a,b){g.V.call(this,{G:"div",
Ia:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},R5=function(a){g.V.call(this,{G:"div",
Ia:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},T:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",T:[{G:"span",L:"ytp-upnext-header",xa:"Up Next"},{G:"span",L:"ytp-upnext-title",xa:"{{title}}"},{G:"span",L:"ytp-upnext-author",xa:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},T:[{G:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
T:[{G:"circle",L:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",T:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
xa:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.D=this.Ga("ytp-svg-autoplay-ring");this.B=this.notification=this.i=this.suggestion=null;this.C=new g.M(this.Kx,5E3,this);this.u=0;var b=this.Ga("ytp-upnext-cancel");this.cancelButton=new g.V({G:"button",Ia:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel autoplay"},xa:"Cancel"});g.J(this,this.cancelButton);this.cancelButton.Sa("click",this.fP,this);this.cancelButton.Fa(b);this.cancelButton&&this.api.Vb(this.cancelButton.element,
this,115129);g.J(this,this.C);this.api.Vb(this.element,this,18788);b=this.Ga("ytp-upnext-autoplay-icon");this.S(b,"click",this.gP);this.api.Vb(b,this,115130);this.UG();this.S(a,"autonavvisibility",this.UG);this.S(a,"mdxnowautoplaying",this.bU);this.S(a,"mdxautoplaycanceled",this.cU);g.O(this.element,"ytp-upnext-mobile",this.api.U().i)},VPa=function(a,b){return b?b:0<=a.api.xp()?a.api.xp():g.T(a.api.U().experiments,"autoplay_time")||1E4},S5=function(a,b){b=VPa(a,b);
var c=Math,d=c.min;var e=(0,g.Q)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Mh()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Mh()&&a.i.start()},T5=function(a){Q5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.V({G:"div",L:"ytp-suggestion-panel",T:[{G:"div",Ia:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],xa:"More videos"}]});this.K=new g.V({G:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.J=!1;this.u=new M5(this.player);g.J(this,this.u);this.u.Fa(this.element);a.getVideoData().jc?this.i=this.u:(this.i=new R5(a),g.XM(this.player,this.i.element,4),g.J(this,this.i));this.overlay=new g.V({G:"div",
L:"ytp-autonav-overlay-cancelled-state"});g.J(this,this.overlay);this.overlay.Fa(this.element);this.C=new g.ID(this);g.J(this,this.C);g.J(this,this.table);this.table.Fa(this.element);this.table.show();g.J(this,this.K);this.K.Fa(this.table.element);this.hide()},U5=function(a){var b=a.Wd();
b!==a.D&&(a.D=b,a.player.Z("autonavvisibility"),a.D?(a.u!==a.i&&a.u.hide(),a.table.hide()):(a.u!==a.i&&a.u.show(),a.table.show()))},V5=function(a){Q5.call(this,a,"subscribecard-endscreen");
this.i=new g.V({G:"div",L:"ytp-subscribe-card",T:[{G:"img",L:"ytp-author-image",W:{src:"{{profilePicture}}"}},{G:"div",L:"ytp-subscribe-card-right",T:[{G:"div",L:"ytp-author-name",xa:"{{author}}"},{G:"div",L:"html5-subscribe-button-container"}]}]});g.J(this,this.i);this.i.Fa(this.element);var b=a.getVideoData();this.subscribeButton=new g.lO("Subscribe",null,"Unsubscribe",null,!0,!1,b.Ui,b.subscribed,"trailer-endscreen",null,null,a);g.J(this,this.subscribeButton);this.subscribeButton.Fa(this.i.Ga("html5-subscribe-button-container"));
this.S(a,"videodatachange",this.Ra);this.Ra();this.hide()},W5=function(a){var b=a.U(),c=g.gj||g.fF?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.i&&e.push("ytp-videowall-show-text");g.V.call(this,{G:"a",Ia:e,W:{href:"{{url}}",target:d?b.K:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},T:[{G:"div",L:"ytp-videowall-still-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",T:[{G:"span",L:"ytp-videowall-still-info-bg",T:[{G:"span",L:"ytp-videowall-still-info-content",W:c,T:[{G:"span",L:"ytp-videowall-still-info-title",xa:"{{title}}"},{G:"span",L:"ytp-videowall-still-info-author",
xa:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",xa:"Live"},{G:"span",L:"ytp-videowall-still-info-duration",xa:"{{duration}}"}]}]}]},{G:"span",Ia:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],T:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",L:"ytp-videowall-still-listlabel-length",T:[" (",{G:"span",xa:"{{playlist_length}}"},")"]}]},{G:"span",Ia:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],T:[{G:"span",
L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",L:"ytp-videowall-still-listlabel-length",xa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.i=new g.ID(this);g.J(this,this.i);this.Sa("click",this.onClick);this.Sa("keypress",this.B);this.i.S(a,"videodatachange",this.rb);a.Tg(this.element,this);this.rb()},X5=function(a){Q5.call(this,a,"videowall-endscreen");
var b=this;this.I=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.K=!1;this.N=null;this.u=new g.ID(this);g.J(this,this.u);this.J=new g.M(function(){g.N(b.element,"ytp-show-tiles")},0);
g.J(this,this.J);var c=new g.V({G:"button",Ia:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},T:[g.fL()]});g.J(this,c);c.Fa(this.element);c.Sa("click",this.kP,this);this.table=new g.YK({G:"div",L:"ytp-endscreen-content"});g.J(this,this.table);this.table.Fa(this.element);c=new g.V({G:"button",Ia:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},T:[g.gL()]});g.J(this,c);c.Fa(this.element);c.Sa("click",this.jP,this);a.getVideoData().jc?this.i=new M5(a,!0):this.i=new R5(a);
g.J(this,this.i);g.XM(this.player,this.i.element,4);this.hide()},Y5=function(a){return g.YM(a.player)&&a.vu()&&!a.C},Z5=function(a){var b=a.Wd();
b!==a.K&&(a.K=b,a.player.Z("autonavvisibility"))},$5=function(a){g.gN.call(this,a);
var b=this;this.endScreen=null;this.i=this.u=this.B=!1;this.listeners=new g.ID(this);g.J(this,this.listeners);this.env=a.U();WPa(a)?(this.B=!0,XPa(this),this.i?this.endScreen=new T5(a):this.endScreen=new X5(this.player)):this.env.Qc?this.endScreen=new V5(this.player):this.endScreen=new Q5(this.player);g.J(this,this.endScreen);g.XM(this.player,this.endScreen.element,4);YPa(this);this.listeners.S(a,"videodatachange",this.rb,this);this.listeners.S(a,g.AA("endscreen"),function(c){b.Fd(c)});
this.listeners.S(a,g.BA("endscreen"),function(c){b.uf(c)})},XPa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.Oh&&a.u===b.jc)return!1;a.i=b.Oh;a.u=b.jc;return!0},WPa=function(a){a=a.U();
return a.Bb&&!a.Qc},YPa=function(a){a.player.bf("endscreen");
var b=a.player.getVideoData();b=new g.xA(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.xA(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});a.player.Md([b,c])};
g.QM.prototype.xp=g.ca(2,function(){return this.app.xp()});
g.ZX.prototype.xp=g.ca(1,function(){return this.getVideoData().kK});g.w(K5,g.V);K5.prototype.select=function(){(this.I.Oj(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ru||void 0)||this.I.Y("web_player_endscreen_double_log_fix_killswitch"))&&this.I.Gb(this.element)};
K5.prototype.onClick=function(a){g.FN(a,this.I,this.i,this.suggestion.sessionData||void 0)&&this.select()};
K5.prototype.u=function(a){switch(a.keyCode){case 13:case 32:g.vu(a)||(this.select(),g.uu(a))}};g.w(M5,g.V);g.k=M5.prototype;g.k.nx=function(a){this.suggestion!==a&&(this.suggestion=a,J5(this.i,a),this.playButton.Va("url",this.suggestion.Ck()),P5(this))};
g.k.Mh=function(){return 0<this.u};
g.k.Ws=function(){this.Mh()||(this.u=Date.now(),L5(this),UPa(this.I,O5(this)),g.O(this.I.getRootNode(),"countdown-running",this.Mh()))};
g.k.hq=function(){this.Am();L5(this);var a=this.i.Ga("ytp-autonav-endscreen-upnext-header");a&&g.Dg(a,"Up next")};
g.k.Am=function(){this.Mh()&&(this.C.stop(),this.u=0)};
g.k.select=function(a){this.I.nextVideo(!1,void 0===a?!1:a);this.Am()};
g.k.TG=function(a){g.FN(a,this.I)&&(a.currentTarget===this.playButton.element?this.I.Gb(this.playButton.element):a.currentTarget===this.i.Ga("ytp-autonav-endscreen-link-container")&&(a=this.i.Ga("ytp-autonav-endscreen-link-container"),this.I.kb(a,!0),this.I.Gb(a)),this.select())};
g.k.eP=function(){this.I.Gb(this.cancelButton.element);g.SM(this.I,!0)};
g.k.SG=function(){var a=this.I.Wd();this.D&&this.Ab!==a&&g.aL(this,a);P5(this);this.I.kb(this.element,a);this.I.kb(this.cancelButton.element,a);this.I.kb(this.i.Ga("ytp-autonav-endscreen-link-container"),a);this.I.kb(this.playButton.element,a)};
g.k.qf=function(a){return 400>a.width||459>a.height};g.w(Q5,g.V);g.k=Q5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.vu=function(){return!1};
g.k.Wd=function(){return!1};
g.k.jK=function(){return!1};g.w(R5,g.V);g.k=R5.prototype;g.k.Kx=function(){this.notification&&(this.C.stop(),this.pc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.nx=function(a){this.suggestion=a;J5(this,a,"hqdefault.jpg")};
g.k.UG=function(){g.aL(this,this.api.Wd());this.api.kb(this.element,this.api.Wd());this.api.kb(this.Ga("ytp-upnext-autoplay-icon"),this.api.Wd());this.cancelButton&&this.api.kb(this.cancelButton.element,this.api.Wd())};
g.k.lU=function(){window.focus();this.Kx()};
g.k.Ws=function(a){var b=this;this.Mh()||(g.Yu("a11y-announce","Up Next "+this.suggestion.title),this.u=(0,g.Q)(),this.i=new g.M(function(){S5(b,a)},25),S5(this,a),UPa(this.api,VPa(this,a)));
g.Qq(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Mh=function(){return!!this.i};
g.k.hq=function(){this.Am();this.u=(0,g.Q)();S5(this);g.N(this.element,"ytp-upnext-autoplay-paused")};
g.k.Am=function(){this.Mh()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.U().experiments.oa("autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.Kx(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Ge()}),this.B=this.S(this.notification,"click",this.lU),this.C.start())}this.Am();this.api.nextVideo(!1,a)};
g.k.gP=function(a){!g.Cg(this.cancelButton.element,g.pu(a))&&g.FN(a,this.api)&&(this.api.Wd()&&this.api.Gb(this.Ga("ytp-upnext-autoplay-icon")),this.select())};
g.k.fP=function(){this.api.Wd()&&this.cancelButton&&this.api.Gb(this.cancelButton.element);g.SM(this.api,!0)};
g.k.bU=function(a){this.api.getPresentingPlayerType();this.show();this.Ws(a)};
g.k.cU=function(){this.api.getPresentingPlayerType();this.Am();this.hide()};
g.k.Aa=function(){this.Am();this.Kx();g.V.prototype.Aa.call(this)};g.w(T5,Q5);g.k=T5.prototype;g.k.create=function(){Q5.prototype.create.call(this);this.C.S(this.player,"appresize",this.Tt);this.C.S(this.player,"onVideoAreaChange",this.Tt);this.C.S(this.player,"videodatachange",this.rb);this.C.S(this.player,"autonavchange",this.VG);this.C.S(this.player,"autonavcancel",this.hP);this.rb()};
g.k.show=function(){Q5.prototype.show.call(this);(this.J||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.SM(this.player,!1);g.YM(this.player)&&this.vu()&&!this.B?(U5(this),2===this.videoData.autonavState?this.player.U().Y("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Ws():3===this.videoData.autonavState&&this.i.hq()):(g.SM(this.player,!0),U5(this));this.Tt()};
g.k.hide=function(){Q5.prototype.hide.call(this);this.i.hq();U5(this)};
g.k.Tt=function(){var a=this.player.jj(!0,this.player.isFullscreen());U5(this);P5(this.u);g.O(this.element,"ytp-autonav-cancelled-small-mode",this.qf(a));g.O(this.element,"ytp-autonav-cancelled-tiny-mode",this.Ty(a));g.O(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Ql(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.r(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.r(b.value);b=c.next().value;c=c.next().value;g.O(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.rb=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){this.i.nx(a[0]);this.i!==this.u&&this.u.nx(a[0]);for(var b=0;b<ZPa.length;++b){var c=ZPa[b];if(a&&a[c]){this.videos[b]=new K5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,J5(d,c));g.J(this,this.videos[b]);this.videos[b].Fa(this.K.element)}}}this.Tt()}};
g.k.VG=function(a){1===a?(this.J=!1,this.B=this.videoData.clientPlaybackNonce,this.i.Am(),this.Ab&&this.Tt()):(this.J=!0,this.Wd()&&(2===a?this.i.Ws():3===a&&this.i.hq()))};
g.k.hP=function(a){a?this.VG(1):(this.B=null,this.J=!1)};
g.k.vu=function(){return 1!==this.videoData.autonavState};
g.k.qf=function(a){return(910>a.width||459>a.height)&&!this.Ty(a)&&!(400>=a.width||360>=a.height)};
g.k.Ty=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Wd=function(){return this.Ab&&g.YM(this.player)&&this.vu()&&!this.B};
var ZPa=[1,3,2,4];g.w(V5,Q5);V5.prototype.Ra=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.Sh,author:a.author});this.subscribeButton.channelId=a.Ui;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.w(W5,g.V);W5.prototype.select=function(){(this.api.Oj(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ru||void 0)||this.api.Y("web_player_endscreen_double_log_fix_killswitch"))&&this.api.Gb(this.element)};
W5.prototype.onClick=function(a){g.FN(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
W5.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.vu(a)||(this.select(),g.uu(a))}};
W5.prototype.rb=function(){var a=this.api.getVideoData(),b=this.api.U();this.u=a.D?!1:b.u};g.w(X5,Q5);g.k=X5.prototype;g.k.create=function(){Q5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.bl();this.u.S(this.player,"appresize",this.bl);this.u.S(this.player,"onVideoAreaChange",this.bl);this.u.S(this.player,"videodatachange",this.rb);this.u.S(this.player,"autonavchange",this.vB);this.u.S(this.player,"autonavcancel",this.iP);a=this.videoData.autonavState;a!==this.N&&this.vB(a);this.u.S(this.element,"transitionend",this.BV)};
g.k.destroy=function(){g.cy(this.u);g.pf(this.stills);this.stills=[];Q5.prototype.destroy.call(this);g.Qq(this.element,"ytp-show-tiles");this.J.stop();this.N=this.videoData.autonavState};
g.k.vu=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){Q5.prototype.show.call(this);g.Qq(this.element,"ytp-show-tiles");this.player.U().i?g.Jq(this.J):this.J.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.SM(this.player,!1);Y5(this)?(Z5(this),2===this.videoData.autonavState?this.player.U().Y("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Ws():3===this.videoData.autonavState&&this.i.hq()):(g.SM(this.player,!0),Z5(this))};
g.k.hide=function(){Q5.prototype.hide.call(this);this.i.hq();Z5(this)};
g.k.BV=function(a){g.pu(a)===this.element&&this.bl()};
g.k.bl=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.N(this.element,"ytp-endscreen-paginate");var a=this.I.jj(!0,this.I.isFullscreen()),b=g.NM(this.I);b&&(b=b.Qe()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,q=e/2,t=b<=f-2&&n>=q*m,u=e<=h-2&&n>=p*m;if((p+
1)/q*d/c>c/(p/(q+1)*d)&&u)n-=p*m,e+=2;else if(t)n-=q*m,b+=2;else if(u)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.dm(a,m,n);g.Ql(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.nx(this.videoData.suggestions[0]);this.i instanceof M5&&P5(this.i);g.O(this.element,"ytp-endscreen-takeover",Y5(this));Z5(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,q=0,d&&f>=b-2&&h>=e-2?q=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(q=2):q=2),p=g.Wf(p+this.B,l),0!==q){t=this.stills[c];t||(t=new W5(this.player),this.stills[c]=t,a.appendChild(t.element));u=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+q)/e)-u-4,A=Math.floor(m*(f+q)/b)-x-4;g.Xl(t.element,x,u);g.dm(t.element,A,y);g.Ql(t.element,"transitionDelay",(h+f)/20+"s");g.O(t.element,"ytp-videowall-still-mini",1===q);g.O(t.element,"ytp-videowall-still-large",
2<q);q=t;p=this.videoData.suggestions[p];q.suggestion!==p&&(q.suggestion=p,t=q.api.U(),u=g.Oq(q.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",J5(q,p,u),g.hF(t)&&(t=p.Ck(),t=g.wi(t,g.FM("emb_rel_end")),q.Va("url",t)),(p=(p=p.sessionData)&&p.itct)&&q.api.ym(q.element,p));c++}g.O(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Ag(e.element),g.of(e);this.stills.length=c}};
g.k.rb=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.bl())};
g.k.jP=function(){this.B+=this.stills.length;this.bl()};
g.k.kP=function(){this.B-=this.stills.length;this.bl()};
g.k.jK=function(){return this.i.Mh()};
g.k.vB=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.i.Am(),this.Ab&&this.bl()):(this.D=!0,this.Ab&&Y5(this)&&(2===a?this.i.Ws():3===a&&this.i.hq()))};
g.k.iP=function(a){if(a){for(a=0;a<this.stills.length;a++)this.I.kb(this.stills[a].element,!0);this.vB(1)}else this.C=null,this.D=!1;this.bl()};
g.k.Wd=function(){return this.Ab&&Y5(this)};g.w($5,g.gN);g.k=$5.prototype;g.k.xq=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!WPa(this.player)||b;var c=a.Ee||g.sF(a.B),d=this.player.Xu();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Wd=function(){return this.endScreen.Wd()};
g.k.OR=function(){return this.Wd()?this.endScreen.jK():!1};
g.k.Aa=function(){this.player.bf("endscreen");g.gN.prototype.Aa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.fI;if(b&&b.videoId){var c=this.player.vb().zd.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.fH?a=!1:(this.player.Oj(b.videoId,void 0,void 0,!0,!0,b),c&&c.ez("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.gN.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.gN.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.Fd=function(a){this.xq()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.uf=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.rb=function(){YPa(this);this.B&&XPa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new T5(this.player):this.endScreen=new X5(this.player),g.J(this,this.endScreen),g.XM(this.player,this.endScreen.element,4))};g.rN.endscreen=$5;})(_yt_player);
